	.align 2
DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_36::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_fend_slap1_pull_36.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_48::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_fend_slap1_pull_48.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_rock_piano_60::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_rock_piano_60.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_rock_piano_72::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_rock_piano_72.bin"

	.align 2
DirectSoundWaveData_bw_independence_pro_khso_all_strings_spc_up::
	.incbin "sound/direct_sound_samples/bw_independence_pro_khso_all_strings_spc_up.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trumpet_ensemble_60::
	.incbin "sound/direct_sound_samples/bw_kfl_trumpet_ensemble_60.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trumpet_ensemble_69::
	.incbin "sound/direct_sound_samples/bw_kfl_trumpet_ensemble_69.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_electric_sitar_48::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_electric_sitar_48.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_electric_sitar_57::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_electric_sitar_57.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_electric_sitar_65::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_electric_sitar_65.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_electric_sitar_74::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_electric_sitar_74.bin"

	.align 2
DirectSoundWaveData_bw_ps15_snare105::
	.incbin "sound/direct_sound_samples/bw_ps15_snare105.bin"

@	.align 2
@DirectSoundWaveData_b2_absynth_square_pad_flange_38::
@	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_38.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_50::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_50.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_62::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_62.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_74::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_74.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_86::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_86.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_38::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_38.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_50::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_50.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_62::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_62.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_74::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_74.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_86::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_86.bin"

@	.align 2
@DirectSoundWaveData_b2_ew_ra_gamelan_48::
@	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_48.bin"
@
@	.align 2
@DirectSoundWaveData_b2_ew_ra_gamelan_55::
@	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_55.bin"
@
@	.align 2
@DirectSoundWaveData_b2_ew_ra_gamelan_60::
@	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_60.bin"

	.align 2
DirectSoundWaveData_b2_ew_ra_gamelan_67::
	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_67.bin"

	.align 2
DirectSoundWaveData_b2_ew_ra_gamelan_72::
	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_72.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove125::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove125.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_29::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_29.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_41::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_41.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_53::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_53.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_65::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_65.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_77::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_77.bin"

	.align 2
DirectSoundWaveData_b2_halion_t9_analog_kick::
	.incbin "sound/direct_sound_samples/b2_halion_t9_analog_kick.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_chemical_house_snare::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_chemical_house_snare.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_floor_tom::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_floor_tom.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_1::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_1.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_2::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_2.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_3::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_3.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_4::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_4.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_5::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_5.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_flute_sus_79::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_flute_sus_79.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_asian_supremacy::
	.incbin "sound/direct_sound_samples/b2_omnisphere_asian_supremacy.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_aggresitronic_beamz::
	.incbin "sound/direct_sound_samples/b2_omnisphere_aggresitronic_beamz.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_room_snare_colress::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_room_snare_colress.bin"

	.align 2
DirectSoundWaveData_b2_ps15_hihat20_loop::
	.incbin "sound/direct_sound_samples/b2_ps15_hihat20_loop.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_snare::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_snare.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove109::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove109.bin"

	.align 2
DirectSoundWaveData_b2_unknown_electronic_kick_dpleader::
	.incbin "sound/direct_sound_samples/b2_unknown_electronic_kick_dpleader.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_classic117::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_classic117.bin"

	.align 2
DirectSoundWaveData_b2_unknown_vocal1_plasma::
	.incbin "sound/direct_sound_samples/b2_unknown_vocal1_plasma.bin"

	.align 2
DirectSoundWaveData_b2_unknown_vocal2_plasma::
	.incbin "sound/direct_sound_samples/b2_unknown_vocal2_plasma.bin"
