	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove125::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove125.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_29::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_29.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_41::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_41.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_53::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_53.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_65::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_65.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_77::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_77.bin"

	.align 2
DirectSoundWaveData_b2_halion_t9_analog_kick::
	.incbin "sound/direct_sound_samples/b2_halion_t9_analog_kick.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_chemical_house_snare::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_chemical_house_snare.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_floor_tom::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_floor_tom.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_1::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_1.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_2::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_2.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_3::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_3.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_4::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_4.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_5::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_5.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_flute_sus_79::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_flute_sus_79.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_asian_supremacy::
	.incbin "sound/direct_sound_samples/b2_omnisphere_asian_supremacy.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_aggresitronic_beamz::
	.incbin "sound/direct_sound_samples/b2_omnisphere_aggresitronic_beamz.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_room_snare_colress::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_room_snare_colress.bin"

	.align 2
DirectSoundWaveData_b2_ps15_hihat20_loop::
	.incbin "sound/direct_sound_samples/b2_ps15_hihat20_loop.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_snare::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_snare.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove109::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove109.bin"

	.align 2
DirectSoundWaveData_b2_unknown_electronic_kick_dpleader::
	.incbin "sound/direct_sound_samples/b2_unknown_electronic_kick_dpleader.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_classic117::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_classic117.bin"

	.align 2
DirectSoundWaveData_b2_unknown_vocal1_plasma::
	.incbin "sound/direct_sound_samples/b2_unknown_vocal1_plasma.bin"

	.align 2
DirectSoundWaveData_b2_unknown_vocal2_plasma::
	.incbin "sound/direct_sound_samples/b2_unknown_vocal2_plasma.bin"

	.align 2
DirectSoundWaveData_k64_drumloop1a::
	.incbin "sound/direct_sound_samples/k64_drumloop1a.bin"

	.align 2
DirectSoundWaveData_k64_drumloop1b::
	.incbin "sound/direct_sound_samples/k64_drumloop1b.bin"

	.align 2
DirectSoundWaveData_k64_drumloop1c::
	.incbin "sound/direct_sound_samples/k64_drumloop1c.bin"

	.align 2
DirectSoundWaveData_k64_tractor_noise::
	.incbin "sound/direct_sound_samples/k64_tractor_noise.bin"

	.align 2
DirectSoundWaveData_k64_tambourine::
	.incbin "sound/direct_sound_samples/k64_tambourine.bin"

	.align 2
DirectSoundWaveData_k64_synthbass0D_24::
	.incbin "sound/direct_sound_samples/k64_synthbass0D_24.bin"

	.align 2
DirectSoundWaveData_k64_synthbass0D_40::
	.incbin "sound/direct_sound_samples/k64_synthbass0D_40.bin"

@	.align 2
@DirectSoundWaveData_k64_synthbass0D_60::
@	.incbin "sound/direct_sound_samples/k64_synthbass0D_60.bin"

	.align 2
DirectSoundWaveData_k64_acidbass2C_36::
	.incbin "sound/direct_sound_samples/k64_acidbass2C_36.bin"

	.align 2
DirectSoundWaveData_k64_acidbass2C_48::
	.incbin "sound/direct_sound_samples/k64_acidbass2C_48.bin"

@	.align 2
@DirectSoundWaveData_k64_acidbass2C_60::
@	.incbin "sound/direct_sound_samples/k64_acidbass2C_60.bin"

	.align 2
DirectSoundWaveData_k64_square1C_69::
	.incbin "sound/direct_sound_samples/k64_square1C_69.bin"

@	.align 2
@DirectSoundWaveData_k64_square1C_81::
@	.incbin "sound/direct_sound_samples/k64_square1C_81.bin"
@
@	.align 2
@DirectSoundWaveData_k64_square1C_93::
@	.incbin "sound/direct_sound_samples/k64_square1C_93.bin"

	.align 2
DirectSoundWaveData_k64_ride::
	.incbin "sound/direct_sound_samples/k64_ride.bin"

	.align 2
DirectSoundWaveData_k64_crash::
	.incbin "sound/direct_sound_samples/k64_crash.bin"

	.align 2
DirectSoundWaveData_k64_hardsynthbrass_69::
	.incbin "sound/direct_sound_samples/k64_hardsynthbrass_69.bin"

@	.align 2
@DirectSoundWaveData_k64_hardsynthbrass_81::
@	.incbin "sound/direct_sound_samples/k64_hardsynthbrass_81.bin"
@
@	.align 2
@DirectSoundWaveData_k64_hardsynthbrass_93::
@	.incbin "sound/direct_sound_samples/k64_hardsynthbrass_93.bin"

	.align 2
DirectSoundWaveData_k64_drumloop2a::
	.incbin "sound/direct_sound_samples/k64_drumloop2a.bin"

	.align 2
DirectSoundWaveData_k64_drumloop2b::
	.incbin "sound/direct_sound_samples/k64_drumloop2b.bin"

	.align 2
DirectSoundWaveData_k64_drumloop2c::
	.incbin "sound/direct_sound_samples/k64_drumloop2c.bin"

@	.align 2
@DirectSoundWaveData_k64_drumloop2d::
@	.incbin "sound/direct_sound_samples/k64_drumloop2d.bin"

	.align 2
DirectSoundWaveData_k64_sfx_kick::
	.incbin "sound/direct_sound_samples/k64_sfx_kick.bin"

	.align 2
DirectSoundWaveData_k64_chh::
	.incbin "sound/direct_sound_samples/k64_chh.bin"

	.align 2
DirectSoundWaveData_k64_orchhit::
	.incbin "sound/direct_sound_samples/k64_orchhit.bin"

	.align 2
DirectSoundWaveData_k64_timpani::
	.incbin "sound/direct_sound_samples/k64_timpani.bin"

	.align 2
DirectSoundWaveData_k64_synthvox0C_36::
	.incbin "sound/direct_sound_samples/k64_synthvox0C_36.bin"

@	.align 2
@DirectSoundWaveData_k64_synthvox0C_57::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_57.bin"
@
@	.align 2
@DirectSoundWaveData_k64_synthvox0C_69::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_69.bin"
@
@	.align 2
@DirectSoundWaveData_k64_synthvox0C_81::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_81.bin"
@
@	.align 2
@DirectSoundWaveData_k64_synthvox0C_93::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_93.bin"

	.align 2
DirectSoundWaveData_k64_pipeorgan_69::
	.incbin "sound/direct_sound_samples/k64_pipeorgan_69.bin"

@	.align 2
@DirectSoundWaveData_k64_pipeorgan_81::
@	.incbin "sound/direct_sound_samples/k64_pipeorgan_81.bin"

	.align 2
DirectSoundWaveData_k64_trumpet_72::
	.incbin "sound/direct_sound_samples/k64_trumpet_72.bin"

@	.align 2
@DirectSoundWaveData_k64_trumpet_84::
@	.incbin "sound/direct_sound_samples/k64_trumpet_84.bin"
