	.align 2
DirectSoundWaveData_b2_ew_ra_chinese_gong_vs::
	.incbin "sound/direct_sound_samples/b2_ew_ra_chinese_gong_vs.bin"

	.align 2
DirectSoundWaveData_b2_ew_ra_chinese_gong_vs_2::
	.incbin "sound/direct_sound_samples/b2_ew_ra_chinese_gong_vs_2.bin"

	.align 2
DirectSoundWaveData_b2_sd90_timpani2_37_22::
	.incbin "sound/direct_sound_samples/b2_sd90_timpani2_37_22.bin"

	.align 2
DirectSoundWaveData_b2_sd90_timpani2_49_22::
	.incbin "sound/direct_sound_samples/b2_sd90_timpani2_49_22.bin"

	.align 2
DirectSoundWaveData_b2_sd90_timpani2_61_22::
	.incbin "sound/direct_sound_samples/b2_sd90_timpani2_61_22.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_khso_all_strings_spc_up_22::
	.incbin "sound/direct_sound_samples/b2_independence_pro_khso_all_strings_spc_up_22.bin"

	.align 2
DirectSoundWaveData_b2_ethno_instrument_taiko_reverb_mic2_loop::
	.incbin "sound/direct_sound_samples/b2_ethno_instrument_taiko_reverb_mic2_loop.bin"

	.align 2
DirectSoundWaveData_b2_ps13_classic_choir_ahh_57_22::
	.incbin "sound/direct_sound_samples/b2_ps13_classic_choir_ahh_57_22.bin"

	.align 2
DirectSoundWaveData_b2_ps13_classic_choir_ahh_65_22::
	.incbin "sound/direct_sound_samples/b2_ps13_classic_choir_ahh_65_22.bin"

	.align 2
DirectSoundWaveData_b2_ps13_classic_choir_ahh_72_22::
	.incbin "sound/direct_sound_samples/b2_ps13_classic_choir_ahh_72_22.bin"

	.align 2
DirectSoundWaveData_b2_kfl_trumpet_ensemble_60cut_22::
	.incbin "sound/direct_sound_samples/b2_kfl_trumpet_ensemble_60cut_22.bin"

	.align 2
DirectSoundWaveData_b2_kfl_trumpet_ensemble_69cut_22::
	.incbin "sound/direct_sound_samples/b2_kfl_trumpet_ensemble_69cut_22.bin"

	.align 2
DirectSoundWaveData_b2_unknown_snare_ghetsis::
	.incbin "sound/direct_sound_samples/b2_unknown_snare_ghetsis.bin"

	.align 2
DirectSoundWaveData_b2_halion_t9_analog_kick_22::
	.incbin "sound/direct_sound_samples/b2_halion_t9_analog_kick_22.bin"

	.align 2
DirectSoundWaveData_b2_sd90_power2_snare_20::
	.incbin "sound/direct_sound_samples/b2_sd90_power2_snare_20.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_tom::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_tom.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_room_snare_ghetsis::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_room_snare_ghetsis.bin"

	.align 2
DirectSoundWaveData_b2_qy70_doublsaw::
	.incbin "sound/direct_sound_samples/b2_qy70_doublsaw.bin"

	.align 2
DirectSoundWaveData_b2_qy70_doublsaw_72::
	.incbin "sound/direct_sound_samples/b2_qy70_doublsaw_72.bin"

	.align 2
DirectSoundWaveData_b2_ew_goliath_pink_strat_40::
	.incbin "sound/direct_sound_samples/b2_ew_goliath_pink_strat_40.bin"

	.align 2
DirectSoundWaveData_b2_ew_goliath_pink_strat_52::
	.incbin "sound/direct_sound_samples/b2_ew_goliath_pink_strat_52.bin"

	.align 2
DirectSoundWaveData_b2_ew_goliath_pink_strat_64::
	.incbin "sound/direct_sound_samples/b2_ew_goliath_pink_strat_64.bin"

	.align 2
DirectSoundWaveData_b2_ew_goliath_pink_strat_69::
	.incbin "sound/direct_sound_samples/b2_ew_goliath_pink_strat_69.bin"

	.align 2
DirectSoundWaveData_b2_ew_goliath_pink_strat_81::
	.incbin "sound/direct_sound_samples/b2_ew_goliath_pink_strat_81.bin"

@	.align 2
@DirectSoundWaveData_b2_absynth_square_pad_flange_38::
@	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_38.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_50::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_50.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_62::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_62.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_74::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_74.bin"

	.align 2
DirectSoundWaveData_b2_absynth_square_pad_flange_86::
	.incbin "sound/direct_sound_samples/b2_absynth_square_pad_flange_86.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_38::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_38.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_50::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_50.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_62::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_62.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_74::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_74.bin"

	.align 2
DirectSoundWaveData_b2_fm8_dj_handy_86::
	.incbin "sound/direct_sound_samples/b2_fm8_dj_handy_86.bin"

@	.align 2
@DirectSoundWaveData_b2_ew_ra_gamelan_48::
@	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_48.bin"
@
@	.align 2
@DirectSoundWaveData_b2_ew_ra_gamelan_55::
@	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_55.bin"
@
@	.align 2
@DirectSoundWaveData_b2_ew_ra_gamelan_60::
@	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_60.bin"

	.align 2
DirectSoundWaveData_b2_ew_ra_gamelan_67::
	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_67.bin"

	.align 2
DirectSoundWaveData_b2_ew_ra_gamelan_72::
	.incbin "sound/direct_sound_samples/b2_ew_ra_gamelan_72.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove125::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove125.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_29::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_29.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_41::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_41.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_53::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_53.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_65::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_65.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_classical_piano1_77::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_classical_piano1_77.bin"

	.align 2
DirectSoundWaveData_b2_halion_t9_analog_kick::
	.incbin "sound/direct_sound_samples/b2_halion_t9_analog_kick.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_chemical_house_snare::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_chemical_house_snare.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_floor_tom::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_floor_tom.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_1::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_1.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_2::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_2.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_3::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_3.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_4::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_4.bin"

	.align 2
DirectSoundWaveData_b2_mike_skinner_5::
	.incbin "sound/direct_sound_samples/b2_mike_skinner_5.bin"

	.align 2
DirectSoundWaveData_b2_plugsound_pro_flute_sus_79::
	.incbin "sound/direct_sound_samples/b2_plugsound_pro_flute_sus_79.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_asian_supremacy::
	.incbin "sound/direct_sound_samples/b2_omnisphere_asian_supremacy.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_aggresitronic_beamz::
	.incbin "sound/direct_sound_samples/b2_omnisphere_aggresitronic_beamz.bin"

	.align 2
DirectSoundWaveData_b2_addictive_drums_room_snare_colress::
	.incbin "sound/direct_sound_samples/b2_addictive_drums_room_snare_colress.bin"

	.align 2
DirectSoundWaveData_b2_ps15_hihat20_loop::
	.incbin "sound/direct_sound_samples/b2_ps15_hihat20_loop.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_snare::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_snare.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove109::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove109.bin"

	.align 2
DirectSoundWaveData_b2_unknown_electronic_kick_dpleader::
	.incbin "sound/direct_sound_samples/b2_unknown_electronic_kick_dpleader.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_classic117::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_classic117.bin"

	.align 2
DirectSoundWaveData_b2_unknown_vocal1_plasma::
	.incbin "sound/direct_sound_samples/b2_unknown_vocal1_plasma.bin"

	.align 2
DirectSoundWaveData_b2_unknown_vocal2_plasma::
	.incbin "sound/direct_sound_samples/b2_unknown_vocal2_plasma.bin"

	.align 2
DirectSoundWaveData_k64_drumloop1a::
	.incbin "sound/direct_sound_samples/k64_drumloop1a.bin"

	.align 2
DirectSoundWaveData_k64_drumloop1b::
	.incbin "sound/direct_sound_samples/k64_drumloop1b.bin"

	.align 2
DirectSoundWaveData_k64_drumloop1c::
	.incbin "sound/direct_sound_samples/k64_drumloop1c.bin"

	.align 2
DirectSoundWaveData_k64_tractor_noise::
	.incbin "sound/direct_sound_samples/k64_tractor_noise.bin"

	.align 2
DirectSoundWaveData_k64_tambourine::
	.incbin "sound/direct_sound_samples/k64_tambourine.bin"

	.align 2
DirectSoundWaveData_k64_synthbass0D_24::
	.incbin "sound/direct_sound_samples/k64_synthbass0D_24.bin"

	.align 2
DirectSoundWaveData_k64_synthbass0D_40::
	.incbin "sound/direct_sound_samples/k64_synthbass0D_40.bin"

@	.align 2
@DirectSoundWaveData_k64_synthbass0D_60::
@	.incbin "sound/direct_sound_samples/k64_synthbass0D_60.bin"

	.align 2
DirectSoundWaveData_k64_acidbass2C_36::
	.incbin "sound/direct_sound_samples/k64_acidbass2C_36.bin"

	.align 2
DirectSoundWaveData_k64_acidbass2C_48::
	.incbin "sound/direct_sound_samples/k64_acidbass2C_48.bin"

@	.align 2
@DirectSoundWaveData_k64_acidbass2C_60::
@	.incbin "sound/direct_sound_samples/k64_acidbass2C_60.bin"

	.align 2
DirectSoundWaveData_k64_square1C_69::
	.incbin "sound/direct_sound_samples/k64_square1C_69.bin"

@	.align 2
@DirectSoundWaveData_k64_square1C_81::
@	.incbin "sound/direct_sound_samples/k64_square1C_81.bin"
@
@	.align 2
@DirectSoundWaveData_k64_square1C_93::
@	.incbin "sound/direct_sound_samples/k64_square1C_93.bin"

	.align 2
DirectSoundWaveData_k64_ride::
	.incbin "sound/direct_sound_samples/k64_ride.bin"

	.align 2
DirectSoundWaveData_k64_crash::
	.incbin "sound/direct_sound_samples/k64_crash.bin"

	.align 2
DirectSoundWaveData_k64_hardsynthbrass_69::
	.incbin "sound/direct_sound_samples/k64_hardsynthbrass_69.bin"

@	.align 2
@DirectSoundWaveData_k64_hardsynthbrass_81::
@	.incbin "sound/direct_sound_samples/k64_hardsynthbrass_81.bin"
@
@	.align 2
@DirectSoundWaveData_k64_hardsynthbrass_93::
@	.incbin "sound/direct_sound_samples/k64_hardsynthbrass_93.bin"

	.align 2
DirectSoundWaveData_k64_drumloop2a::
	.incbin "sound/direct_sound_samples/k64_drumloop2a.bin"

	.align 2
DirectSoundWaveData_k64_drumloop2b::
	.incbin "sound/direct_sound_samples/k64_drumloop2b.bin"

	.align 2
DirectSoundWaveData_k64_drumloop2c::
	.incbin "sound/direct_sound_samples/k64_drumloop2c.bin"

@	.align 2
@DirectSoundWaveData_k64_drumloop2d::
@	.incbin "sound/direct_sound_samples/k64_drumloop2d.bin"

	.align 2
DirectSoundWaveData_k64_sfx_kick::
	.incbin "sound/direct_sound_samples/k64_sfx_kick.bin"

	.align 2
DirectSoundWaveData_k64_chh::
	.incbin "sound/direct_sound_samples/k64_chh.bin"

	.align 2
DirectSoundWaveData_k64_orchhit::
	.incbin "sound/direct_sound_samples/k64_orchhit.bin"

	.align 2
DirectSoundWaveData_k64_timpani::
	.incbin "sound/direct_sound_samples/k64_timpani.bin"

	.align 2
DirectSoundWaveData_k64_synthvox0C_36::
	.incbin "sound/direct_sound_samples/k64_synthvox0C_36.bin"

@	.align 2
@DirectSoundWaveData_k64_synthvox0C_57::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_57.bin"
@
@	.align 2
@DirectSoundWaveData_k64_synthvox0C_69::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_69.bin"
@
@	.align 2
@DirectSoundWaveData_k64_synthvox0C_81::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_81.bin"
@
@	.align 2
@DirectSoundWaveData_k64_synthvox0C_93::
@	.incbin "sound/direct_sound_samples/k64_synthvox0C_93.bin"

	.align 2
DirectSoundWaveData_k64_pipeorgan_69::
	.incbin "sound/direct_sound_samples/k64_pipeorgan_69.bin"

@	.align 2
@DirectSoundWaveData_k64_pipeorgan_81::
@	.incbin "sound/direct_sound_samples/k64_pipeorgan_81.bin"

	.align 2
DirectSoundWaveData_k64_trumpet_72::
	.incbin "sound/direct_sound_samples/k64_trumpet_72.bin"

@	.align 2
@DirectSoundWaveData_k64_trumpet_84::
@	.incbin "sound/direct_sound_samples/k64_trumpet_84.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_reso_bass_33::
	.incbin "sound/direct_sound_samples/b2_independence_pro_reso_bass_33.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_reso_bass_38::
	.incbin "sound/direct_sound_samples/b2_independence_pro_reso_bass_38.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_hihat_closed::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_hihat_closed.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_hihat_open::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_hihat_open.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_power_chords_combi_1::
	.incbin "sound/direct_sound_samples/b2_independence_pro_power_chords_combi_1.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_power_chords_combi_2::
	.incbin "sound/direct_sound_samples/b2_independence_pro_power_chords_combi_2.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_power_chords_combi_3::
	.incbin "sound/direct_sound_samples/b2_independence_pro_power_chords_combi_3.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_classic138::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_classic138.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove135::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove135.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove135_flange::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove135_flange.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove135funk_1l::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove135funk_1l.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove135funk_1r::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove135funk_1r.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove135funk_2l::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove135funk_2l.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove135funk_2r::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove135funk_2r.bin"

	.align 2
DirectSoundWaveData_b2_unknown_kick_rsleader::
	.incbin "sound/direct_sound_samples/b2_unknown_kick_rsleader.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_aggressive_tendencies::
	.incbin "sound/direct_sound_samples/b2_omnisphere_aggressive_tendencies.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_1::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_1.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_2::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_2.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_3::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_3.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_4::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_4.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_5::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_5.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_6::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_6.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_7::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_7.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_8::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_8.bin"

	.align 2
DirectSoundWaveData_undertale_vanish::
	.incbin "sound/direct_sound_samples/undertale_vanish.bin"
