ProgrammableWaveData_pmd1_000::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_000.pcm"

ProgrammableWaveData_pmd1_001::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_001.pcm"

ProgrammableWaveData_pmd1_002::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_002.pcm"

ProgrammableWaveData_pmd1_003::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_003.pcm"

ProgrammableWaveData_pmd1_004::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_004.pcm"

ProgrammableWaveData_pmd1_005::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_005.pcm"

ProgrammableWaveData_pmd1_006::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_006.pcm"

ProgrammableWaveData_pmd1_007::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_007.pcm"

ProgrammableWaveData_pmd1_008::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_008.pcm"

ProgrammableWaveData_pmd1_009::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_009.pcm"

ProgrammableWaveData_pmd1_010::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_010.pcm"

ProgrammableWaveData_pmd1_011::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_011.pcm"

ProgrammableWaveData_pmd1_012::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_012.pcm"

ProgrammableWaveData_pmd1_013::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_013.pcm"

ProgrammableWaveData_pmd1_014::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_014.pcm"

ProgrammableWaveData_pmd1_015::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_015.pcm"

ProgrammableWaveData_pmd1_016::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_016.pcm"

ProgrammableWaveData_pmd1_017::
	.incbin "sound/programmable_wave_samples/pmd1/gbwave_017.pcm"

ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

@ Unused
ProgrammableWaveData_17::
	.incbin "sound/programmable_wave_samples/17.pcm"

@ Unused
ProgrammableWaveData_18::
	.incbin "sound/programmable_wave_samples/18.pcm"

@ Unused
ProgrammableWaveData_19::
	.incbin "sound/programmable_wave_samples/19.pcm"

@ Unused
ProgrammableWaveData_20::
	.incbin "sound/programmable_wave_samples/20.pcm"

ProgrammableWaveData_21::
	.incbin "sound/programmable_wave_samples/21.pcm"

ProgrammableWaveData_22::
	.incbin "sound/programmable_wave_samples/22.pcm"

ProgrammableWaveData_23::
	.incbin "sound/programmable_wave_samples/23.pcm"

ProgrammableWaveData_24::
	.incbin "sound/programmable_wave_samples/24.pcm"

ProgrammableWaveData_25::
	.incbin "sound/programmable_wave_samples/25.pcm"
