    .align 2
ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

    .align 2
ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

    .align 2
ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

    .align 2
ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

    .align 2
ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

    .align 2
ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

    .align 2
ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

    .align 2
ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

    .align 2
ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

    .align 2
ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

    .align 2
ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

    .align 2
ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

    .align 2
ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

    .align 2
ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

    .align 2
ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

    .align 2
ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

@ Unused
    .align 2
ProgrammableWaveData_17::
	.incbin "sound/programmable_wave_samples/17.pcm"

@ Unused
    .align 2
ProgrammableWaveData_18::
	.incbin "sound/programmable_wave_samples/18.pcm"

@ Unused
    .align 2
ProgrammableWaveData_19::
	.incbin "sound/programmable_wave_samples/19.pcm"

@ Unused
    .align 2
ProgrammableWaveData_20::
	.incbin "sound/programmable_wave_samples/20.pcm"

    .align 2
ProgrammableWaveData_21::
	.incbin "sound/programmable_wave_samples/21.pcm"

    .align 2
ProgrammableWaveData_22::
	.incbin "sound/programmable_wave_samples/22.pcm"

    .align 2
ProgrammableWaveData_23::
	.incbin "sound/programmable_wave_samples/23.pcm"

    .align 2
ProgrammableWaveData_24::
	.incbin "sound/programmable_wave_samples/24.pcm"

    .align 2
ProgrammableWaveData_25::
	.incbin "sound/programmable_wave_samples/25.pcm"

ProgrammableWaveData_nesTri::
	.byte 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98
	.byte 0x76, 0x54, 0x32, 0x10, 0x01, 0x23, 0x45, 0x67

ProgrammableWaveData_saw::
	.byte 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff
	.byte 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77

ProgrammableWaveData_SynString::
	.byte 0x76, 0x67, 0x88, 0x76, 0x54, 0x32, 0x00, 0x03
	.byte 0x56, 0x79, 0xcd, 0xee, 0xdc, 0xcc, 0xba, 0x98
