.include "sound/voicegroups/dummy.inc"

@ drumsets
.include "sound/voicegroups/drumsets/rs.inc"
.include "sound/voicegroups/drumsets/frlg.inc"
.include "sound/voicegroups/drumsets/emerald_1.inc"
.include "sound/voicegroups/drumsets/emerald_2.inc"

@ key splits
.include "sound/voicegroups/keysplits/piano.inc"
.include "sound/voicegroups/keysplits/strings.inc"
.include "sound/voicegroups/keysplits/trumpet.inc"
.include "sound/voicegroups/keysplits/tuba.inc"
.include "sound/voicegroups/keysplits/french_horn.inc"

.if MUX_GRP_ROUTE110 == TRUE
    .include "sound/voicegroups/route110.inc"
.endif
.if MUX_GRP_ROUTE101 == TRUE
    .include "sound/voicegroups/route101.inc"
.endif
.if MUX_GRP_FANFARE == TRUE
    .include "sound/voicegroups/fanfare.inc"
.endif
.if MUX_GRP_GYM == TRUE
    .include "sound/voicegroups/gym.inc"
.endif
.if MUX_GRP_ROUTE120 == TRUE
    .include "sound/voicegroups/route120.inc"
.endif
.if MUX_GRP_PETALBURG == TRUE
    .include "sound/voicegroups/petalburg.inc"
.endif
    .include "sound/voicegroups/drumsets/petalburg.inc"
.if MUX_GRP_SURF == TRUE
    .include "sound/voicegroups/surf.inc"
.endif
.if MUX_GRP_PETALBURG_WOODS == TRUE
    .include "sound/voicegroups/petalburg_woods.inc"
.endif
.if MUX_GRP_OLDALE == TRUE
    .include "sound/voicegroups/oldale.inc"
.endif
.if MUX_GRP_LILYCOVE_MUSEUM == TRUE
    .include "sound/voicegroups/lilycove_museum.inc"
.endif
.if MUX_GRP_ROUTE122 == TRUE
    .include "sound/voicegroups/route122.inc"
.endif
    .include "sound/voicegroups/drumsets/route101.inc"
.if MUX_GRP_OCEANIC_MUSEUM == TRUE
    .include "sound/voicegroups/oceanic_museum.inc"
.endif
.if MUX_GRP_VICTORY_GYM_LEADER == TRUE
    .include "sound/voicegroups/victory_gym_leader.inc"
.endif
.if MUX_GRP_VICTORY_WILD == TRUE
    .include "sound/voicegroups/victory_wild.inc"
.endif
.if MUX_GRP_EVOLUTION == TRUE
    .include "sound/voicegroups/evolution.inc"
.endif
.if MUX_GRP_ENCOUNTER_GIRL == TRUE
    .include "sound/voicegroups/encounter_girl.inc"
.endif
.if MUX_GRP_ENCOUNTER_MALE == TRUE
    .include "sound/voicegroups/encounter_male.inc"
.endif
.if MUX_GRP_VICTORY_LEAGUE == TRUE
    .include "sound/voicegroups/victory_league.inc"
.endif
.if MUX_GRP_ABANDONED_SHIP == TRUE
    .include "sound/voicegroups/abandoned_ship.inc"
.endif
    .include "sound/voicegroups/drumsets/route110.inc"
.if MUX_GRP_FORTREE == TRUE
    .include "sound/voicegroups/fortree.inc"
.endif
.if MUX_GRP_BIRCH_LAB == TRUE
    .include "sound/voicegroups/birch_lab.inc"
.endif
.if MUX_GRP_LITTLEROOT_TEST == TRUE
    .include "sound/voicegroups/littleroot_test.inc"
.endif
.if MUX_GRP_B_TOWER_RS == TRUE
    .include "sound/voicegroups/b_tower_rs.inc"
.endif
.if MUX_GRP_ENCOUNTER_SWIMMER == TRUE
    .include "sound/voicegroups/encounter_swimmer.inc"
.endif
.if MUX_GRP_CAVE_OF_ORIGIN == TRUE
    .include "sound/voicegroups/cave_of_origin.inc"
.endif
.if MUX_GRP_ROULETTE == TRUE
    .include "sound/voicegroups/roulette.inc"
.endif
.if MUX_GRP_LINK_CONTEST_P1 == TRUE
    .include "sound/voicegroups/link_contest_p1.inc"
.endif
.if MUX_GRP_LINK_CONTEST_P2 == TRUE
    .include "sound/voicegroups/link_contest_p2.inc"
.endif
.if MUX_GRP_LINK_CONTEST_P3 == TRUE
    .include "sound/voicegroups/link_contest_p3.inc"
.endif
.if MUX_GRP_LINK_CONTEST_P4 == TRUE
    .include "sound/voicegroups/link_contest_p4.inc"
.endif
.if MUX_GRP_ENCOUNTER_RICH == TRUE
    .include "sound/voicegroups/encounter_rich.inc"
.endif
.if MUX_GRP_VERDANTURF == TRUE
    .include "sound/voicegroups/verdanturf.inc"
.endif
.if MUX_GRP_RUSTBORO == TRUE
    .include "sound/voicegroups/rustboro.inc"
.endif
.if MUX_GRP_POKE_CENTER == TRUE
    .include "sound/voicegroups/poke_center.inc"
.endif
.if MUX_GRP_ROUTE104 == TRUE
    .include "sound/voicegroups/route104.inc"
.endif
.if MUX_GRP_ROUTE119 == TRUE
    .include "sound/voicegroups/route119.inc"
.endif
.if MUX_GRP_CYCLING == TRUE
    .include "sound/voicegroups/cycling.inc"
.endif
.if MUX_GRP_POKE_MART == TRUE
    .include "sound/voicegroups/poke_mart.inc"
.endif
.if MUX_GRP_LITTLEROOT == TRUE
    .include "sound/voicegroups/littleroot.inc"
.endif
.if MUX_GRP_MT_CHIMNEY == TRUE
    .include "sound/voicegroups/mt_chimney.inc"
.endif
.if MUX_GRP_ENCOUNTER_FEMALE == TRUE
    .include "sound/voicegroups/encounter_female.inc"
.endif
.if MUX_GRP_LILYCOVE == TRUE
    .include "sound/voicegroups/lilycove.inc"
.endif
.if MUX_GRP_ROUTE111 == TRUE
    .include "sound/voicegroups/route111.inc"
.endif
.if MUX_GRP_HELP == TRUE
    .include "sound/voicegroups/help.inc"
.endif
.if MUX_GRP_UNDERWATER == TRUE
    .include "sound/voicegroups/underwater.inc"
.endif
.if MUX_GRP_VICTORY_TRAINER == TRUE
    .include "sound/voicegroups/victory_trainer.inc"
.endif
.if MUX_GRP_TITLE == TRUE
    .include "sound/voicegroups/title.inc"
.endif
.if MUX_GRP_INTRO == TRUE
    .include "sound/voicegroups/intro.inc"
.endif
.if MUX_GRP_ENCOUNTER_MAY == TRUE
    .include "sound/voicegroups/encounter_may.inc"
.endif
.if MUX_GRP_ENCOUNTER_INTENSE == TRUE
    .include "sound/voicegroups/encounter_intense.inc"
.endif
.if MUX_GRP_ENCOUNTER_COOL == TRUE
    .include "sound/voicegroups/encounter_cool.inc"
.endif
.if MUX_GRP_ROUTE113 == TRUE
    .include "sound/voicegroups/route113.inc"
.endif
.if MUX_GRP_ENCOUNTER_AQUA == TRUE
    .include "sound/voicegroups/encounter_aqua.inc"
.endif
.if MUX_GRP_FOLLOW_ME == TRUE
    .include "sound/voicegroups/follow_me.inc"
.endif
.if MUX_GRP_ENCOUNTER_BRENDAN == TRUE
    .include "sound/voicegroups/encounter_brendan.inc"
.endif
.if MUX_GRP_EVER_GRANDE == TRUE
    .include "sound/voicegroups/ever_grande.inc"
.endif
.if MUX_GRP_ENCOUNTER_SUSPICIOUS == TRUE
    .include "sound/voicegroups/encounter_suspicious.inc"
.endif
.if MUX_GRP_VICTORY_AQUA_MAGMA == TRUE
    .include "sound/voicegroups/victory_aqua_magma.inc"
.endif
.if MUX_GRP_CABLE_CAR == TRUE
    .include "sound/voicegroups/cable_car.inc"
.endif
.if MUX_GRP_GAME_CORNER == TRUE
    .include "sound/voicegroups/game_corner.inc"
.endif
.if MUX_GRP_DEWFORD == TRUE
    .include "sound/voicegroups/dewford.inc"
.endif
.if MUX_GRP_SAFARI_ZONE == TRUE
    .include "sound/voicegroups/safari_zone.inc"
.endif
.if MUX_GRP_VICTORY_ROAD == TRUE
    .include "sound/voicegroups/victory_road.inc"
.endif
.if MUX_GRP_AQUA_MAGMA_HIDEOUT == TRUE
    .include "sound/voicegroups/aqua_magma_hideout.inc"
.endif
.if MUX_GRP_SAILING == TRUE
    .include "sound/voicegroups/sailing.inc"
.endif
.if MUX_GRP_MT_PYRE == TRUE
    .include "sound/voicegroups/mt_pyre.inc"
.endif
.if MUX_GRP_SLATEPORT == TRUE
    .include "sound/voicegroups/slateport.inc"
.endif
.if MUX_GRP_MT_PYRE_EXTERIOR == TRUE
    .include "sound/voicegroups/mt_pyre_exterior.inc"
.endif
.if MUX_GRP_SCHOOL == TRUE
    .include "sound/voicegroups/school.inc"
.endif
.if MUX_GRP_HALL_OF_FAME == TRUE
    .include "sound/voicegroups/hall_of_fame.inc"
.endif
.if MUX_GRP_FALLARBOR == TRUE
    .include "sound/voicegroups/fallarbor.inc"
.endif
.if MUX_GRP_SEALED_CHAMBER == TRUE
    .include "sound/voicegroups/sealed_chamber.inc"
.endif
.if MUX_GRP_CONTEST_WINNER == TRUE
    .include "sound/voicegroups/contest_winner.inc"
.endif
.if MUX_GRP_CONTEST == TRUE
    .include "sound/voicegroups/contest.inc"
.endif
.if MUX_GRP_ENCOUNTER_MAGMA == TRUE
    .include "sound/voicegroups/encounter_magma.inc"
.endif
.if MUX_GRP_INTRO_BATTLE == TRUE
    .include "sound/voicegroups/intro_battle.inc"
.endif
.if MUX_GRP_ABNORMAL_WEATHER == TRUE
    .include "sound/voicegroups/abnormal_weather.inc"
.endif
.if MUX_GRP_WEATHER_GROUDON == TRUE
    .include "sound/voicegroups/weather_groudon.inc"
.endif
.if MUX_GRP_SOOTOPOLIS == TRUE
    .include "sound/voicegroups/sootopolis.inc"
.endif
.if MUX_GRP_CONTEST_RESULTS == TRUE
    .include "sound/voicegroups/contest_results.inc"
.endif
.if MUX_GRP_HALL_OF_FAME_ROOM == TRUE
    .include "sound/voicegroups/hall_of_fame_room.inc"
.endif
.if MUX_GRP_TRICK_HOUSE == TRUE
    .include "sound/voicegroups/trick_house.inc"
.endif
.if MUX_GRP_ENCOUNTER_TWINS == TRUE
    .include "sound/voicegroups/encounter_twins.inc"
.endif
.if MUX_GRP_ENCOUNTER_ELITE_FOUR == TRUE
    .include "sound/voicegroups/encounter_elite_four.inc"
.endif
.if MUX_GRP_ENCOUNTER_HIKER == TRUE
    .include "sound/voicegroups/encounter_hiker.inc"
.endif
.if MUX_GRP_CONTEST_LOBBY == TRUE
    .include "sound/voicegroups/contest_lobby.inc"
.endif
.if MUX_GRP_ENCOUNTER_INTERVIEWER == TRUE
    .include "sound/voicegroups/encounter_interviewer.inc"
.endif
.if MUX_GRP_ENCOUNTER_CHAMPION == TRUE
    .include "sound/voicegroups/encounter_champion.inc"
.endif
.if MUX_GRP_CREDITS == TRUE
    .include "sound/voicegroups/credits.inc"
.endif
.if MUX_GRP_END == TRUE
    .include "sound/voicegroups/end.inc"
.endif
.if MUX_GRP_B_FRONTIER == TRUE
    .include "sound/voicegroups/b_frontier.inc"
.endif
.if MUX_GRP_B_ARENA == TRUE
    .include "sound/voicegroups/b_arena.inc"
.endif
.if MUX_GRP_REGISTER_MATCH_CALL == TRUE
    .include "sound/voicegroups/register_match_call.inc"
.endif
.if MUX_GRP_B_PYRAMID == TRUE
    .include "sound/voicegroups/b_pyramid.inc"
.endif
.if MUX_GRP_B_PYRAMID_TOP == TRUE
    .include "sound/voicegroups/b_pyramid_top.inc"
.endif
.if MUX_GRP_B_PALACE == TRUE
    .include "sound/voicegroups/b_palace.inc"
.endif
.if MUX_GRP_RAYQUAZA_APPEARS == TRUE
    .include "sound/voicegroups/rayquaza_appears.inc"
.endif
.if MUX_GRP_B_TOWER == TRUE
    .include "sound/voicegroups/b_tower.inc"
.endif
.if MUX_GRP_B_DOME == TRUE
    .include "sound/voicegroups/b_dome.inc"
.endif
.if MUX_GRP_B_PIKE == TRUE
    .include "sound/voicegroups/b_pike.inc"
.endif
.if MUX_GRP_B_FACTORY == TRUE
    .include "sound/voicegroups/b_factory.inc"
.endif
.if MUX_GRP_VS_RAYQUAZA == TRUE
    .include "sound/voicegroups/vs_rayquaza.inc"
.endif
.if MUX_GRP_VS_FRONTIER_BRAIN == TRUE
    .include "sound/voicegroups/vs_frontier_brain.inc"
.endif
.if MUX_GRP_VS_MEW == TRUE
    .include "sound/voicegroups/vs_mew.inc"
.endif
.if MUX_GRP_VS_WILD == TRUE
    .include "sound/voicegroups/vs_wild.inc"
.endif
.if MUX_GRP_VS_AQUA_MAGMA == TRUE
    .include "sound/voicegroups/vs_aqua_magma.inc"
.endif
.if MUX_GRP_VS_TRAINER == TRUE
    .include "sound/voicegroups/vs_trainer.inc"
.endif
.if MUX_GRP_VS_GYM_LEADER == TRUE
    .include "sound/voicegroups/vs_gym_leader.inc"
.endif
.if MUX_GRP_VS_CHAMPION == TRUE
    .include "sound/voicegroups/vs_champion.inc"
.endif
.if MUX_GRP_VS_REGI == TRUE
    .include "sound/voicegroups/vs_regi.inc"
.endif
.if MUX_GRP_VS_KYOGRE_GROUDON == TRUE
    .include "sound/voicegroups/vs_kyogre_groudon.inc" @ duplicate of vs_rayquaza
.endif
.if MUX_GRP_VS_RIVAL == TRUE
    .include "sound/voicegroups/vs_rival.inc"
.endif
.if MUX_GRP_VS_ELITE_FOUR == TRUE
    .include "sound/voicegroups/vs_elite_four.inc"
.endif
.if MUX_GRP_VS_AQUA_MAGMA_LEADER == TRUE
    .include "sound/voicegroups/vs_aqua_magma_leader.inc"
.endif
.if MUX_GRP_RS_SFX_1 == TRUE
    .include "sound/voicegroups/rs_sfx_1.inc"
.endif
.if MUX_GRP_RS_SFX_2 == TRUE
    .include "sound/voicegroups/rs_sfx_2.inc"
.endif

    .include "sound/cry_tables.inc"

.if MUX_GRP_FRLG_SFX == TRUE
    .include "sound/voicegroups/frlg_sfx.inc"
.endif
.if MUX_GRP_BARD == TRUE
    .include "sound/voicegroups/bard.inc"
.endif

@ FRLG
.if MUX_GRP_RG_FOLLOW_ME == TRUE
    .include "sound/voicegroups/rg_follow_me.inc"
.endif
.if MUX_GRP_RG_GAME_CORNER == TRUE
    .include "sound/voicegroups/rg_game_corner.inc"
.endif
.if MUX_GRP_RG_ROCKET_HIDEOUT == TRUE
    .include "sound/voicegroups/rg_rocket_hideout.inc"
.endif
.if MUX_GRP_RG_GYM == TRUE
    .include "sound/voicegroups/rg_gym.inc"
.endif
.if MUX_GRP_RG_JIGGLYPUFF == TRUE
    .include "sound/voicegroups/rg_jigglypuff.inc"
.endif
.if MUX_GRP_RG_INTRO_FIGHT == TRUE
    .include "sound/voicegroups/rg_intro_fight.inc"
.endif
.if MUX_GRP_RG_TITLE == TRUE
    .include "sound/voicegroups/rg_title.inc"
.endif
.if MUX_GRP_RG_CINNABAR == TRUE
    .include "sound/voicegroups/rg_cinnabar.inc"
.endif
.if MUX_GRP_RG_LAVENDER == TRUE
    .include "sound/voicegroups/rg_lavender.inc"
.endif
.if MUX_GRP_RG_HEAL == TRUE
    .include "sound/voicegroups/rg_heal.inc"
.endif
.if MUX_GRP_RG_CYCLING == TRUE
    .include "sound/voicegroups/rg_cycling.inc"
.endif
.if MUX_GRP_RG_ENCOUNTER_ROCKET == TRUE
    .include "sound/voicegroups/rg_encounter_rocket.inc"
.endif
.if MUX_GRP_RG_ENCOUNTER_GIRL == TRUE
    .include "sound/voicegroups/rg_encounter_girl.inc"
.endif
.if MUX_GRP_RG_ENCOUNTER_BOY == TRUE
    .include "sound/voicegroups/rg_encounter_boy.inc"
.endif
.if MUX_GRP_RG_HALL_OF_FAME == TRUE
    .include "sound/voicegroups/rg_hall_of_fame.inc"
.endif
.if MUX_GRP_RG_VIRIDIAN_FOREST == TRUE
    .include "sound/voicegroups/rg_viridian_forest.inc"
.endif
.if MUX_GRP_RG_MT_MOON == TRUE
    .include "sound/voicegroups/rg_mt_moon.inc"
.endif
.if MUX_GRP_RG_POKE_MANSION == TRUE
    .include "sound/voicegroups/rg_poke_mansion.inc"
.endif
.if MUX_GRP_RG_CREDITS == TRUE
    .include "sound/voicegroups/rg_credits.inc"
.endif
.if MUX_GRP_RG_ROUTE1 == TRUE
    .include "sound/voicegroups/rg_route1.inc"
.endif
.if MUX_GRP_RG_ROUTE24 == TRUE
    .include "sound/voicegroups/rg_route24.inc"
.endif
.if MUX_GRP_RG_ROUTE3 == TRUE
    .include "sound/voicegroups/rg_route3.inc"
.endif
.if MUX_GRP_RG_ROUTE11 == TRUE
    .include "sound/voicegroups/rg_route11.inc"
.endif
.if MUX_GRP_RG_VICTORY_ROAD == TRUE
    .include "sound/voicegroups/rg_victory_road.inc"
.endif
.if MUX_GRP_RG_VS_GYM_LEADER == TRUE
    .include "sound/voicegroups/rg_vs_gym_leader.inc"
.endif
.if MUX_GRP_RG_VS_TRAINER == TRUE
    .include "sound/voicegroups/rg_vs_trainer.inc"
.endif
.if MUX_GRP_RG_VS_WILD == TRUE
    .include "sound/voicegroups/rg_vs_wild.inc"
.endif
.if MUX_GRP_RG_VS_CHAMPION == TRUE
    .include "sound/voicegroups/rg_vs_champion.inc"
.endif
.if MUX_GRP_RG_PALLET == TRUE
    .include "sound/voicegroups/rg_pallet.inc"
.endif
.if MUX_GRP_RG_OAK_LAB == TRUE
    .include "sound/voicegroups/rg_oak_lab.inc"
.endif
.if MUX_GRP_RG_OAK == TRUE
    .include "sound/voicegroups/rg_oak.inc"
.endif
.if MUX_GRP_RG_POKE_CENTER == TRUE
    .include "sound/voicegroups/rg_poke_center.inc"
.endif
.if MUX_GRP_RG_SS_ANNE == TRUE
    .include "sound/voicegroups/rg_ss_anne.inc"
.endif
.if MUX_GRP_RG_SURF == TRUE
    .include "sound/voicegroups/rg_surf.inc"
.endif
.if MUX_GRP_RG_POKE_TOWER == TRUE
    .include "sound/voicegroups/rg_poke_tower.inc"
.endif
.if MUX_GRP_RG_SILPH == TRUE
    .include "sound/voicegroups/rg_silph.inc"
.endif
.if MUX_GRP_RG_FUCHSIA == TRUE
    .include "sound/voicegroups/rg_fuchsia.inc"
.endif
.if MUX_GRP_RG_CELADON == TRUE
    .include "sound/voicegroups/rg_celadon.inc"
.endif
.if MUX_GRP_RG_VICTORY_TRAINER == TRUE
    .include "sound/voicegroups/rg_victory_trainer.inc"
.endif
.if MUX_GRP_RG_VICTORY_WILD == TRUE
    .include "sound/voicegroups/rg_victory_wild.inc"
.endif
.if MUX_GRP_RG_VICTORY_GYM_LEADER == TRUE
    .include "sound/voicegroups/rg_victory_gym_leader.inc"
.endif
.if MUX_GRP_RG_VERMILLION == TRUE
    .include "sound/voicegroups/rg_vermillion.inc"
.endif
.if MUX_GRP_RG_PEWTER == TRUE
    .include "sound/voicegroups/rg_pewter.inc"
.endif
.if MUX_GRP_RG_ENCOUNTER_RIVAL == TRUE
    .include "sound/voicegroups/rg_encounter_rival.inc"
.endif
.if MUX_GRP_RG_DEX_RATING == TRUE
    .include "sound/voicegroups/rg_dex_rating.inc"
.endif

    .include "sound/voicegroups/drumsets/frlg_fanfare_2.inc"
    .include "sound/voicegroups/drumsets/frlg_fanfare_1.inc"

.if MUX_GRP_RG_OBTAIN_KEY_ITEM == TRUE
    .include "sound/voicegroups/rg_obtain_key_item.inc"
.endif
.if MUX_GRP_RG_CAUGHT_INTRO == TRUE
    .include "sound/voicegroups/rg_caught_intro.inc"
.endif
.if MUX_GRP_RG_PHOTO == TRUE
    .include "sound/voicegroups/rg_photo.inc"
.endif
.if MUX_GRP_RG_GAME_FREAK == TRUE
    .include "sound/voicegroups/rg_game_freak.inc"
.endif
.if MUX_GRP_RG_NEW_GAME == TRUE
    .include "sound/voicegroups/rg_new_game.inc"
.endif
.if MUX_GRP_RG_MYSTERY_GIFT == TRUE
    .include "sound/voicegroups/rg_mystery_gift.inc"
.endif
.if MUX_GRP_RG_ENCOUNTER_DEOXYS == TRUE
    .include "sound/voicegroups/rg_encounter_deoxys.inc"
.endif
.if MUX_GRP_RG_VS_DEOXYS == TRUE
    .include "sound/voicegroups/rg_vs_deoxys.inc"
.endif
.if MUX_GRP_RG_TEACHY_TV_MENU == TRUE
    .include "sound/voicegroups/rg_teachy_tv_menu.inc"
.endif
.if MUX_GRP_RG_SEVII_ROUTE == TRUE
    .include "sound/voicegroups/rg_sevii_route.inc"
.endif
.if MUX_GRP_RG_SEVII_45 == TRUE
    .include "sound/voicegroups/rg_sevii_45.inc"
.endif
.if MUX_GRP_RG_SEVII_67 == TRUE
    .include "sound/voicegroups/rg_sevii_67.inc"
.endif

    .include "sound/voicegroups/drumsets/rg_credits.inc"
