voice_group test_4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 48, 0, DirectSoundWaveData_wb_harpsichord_c3_32, A(127), D(60), S(1), R(118)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 72, 0, DirectSoundWaveData_wb_glocken_c5_32, A(127), D(75), S(1), R(116)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_wb_n_organ, keysplit_2oct - 7
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_wb_europat_c3_16, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 36, 0, DirectSoundWaveData_wb_synth_bass_c2_32, A(127), D(125), S(120), R(120)
	voice_directsound 35, 0, DirectSoundWaveData_wb_cool3_basE0_22, A(127), D(125), S(120), R(127)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_wb_flute_akai, keysplit_2oct - 16
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 43, 0, DirectSoundWaveData_wb_trombone_g2_22, A(127), D(100), S(100), R(116)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_wb_french_horn, keysplit_2oct - 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 46, 0, DirectSoundWaveData_wb_timpani2_as_16, A(127), D(80), S(1), R(116)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 30, 0, DirectSoundWaveData_wb_synbass_fs0_32, A(127), D(75), S(1), R(116)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 72, 0, DirectSoundWaveData_wb_pbrasslop_c4_max32, A(127), D(127), S(127), R(120)
	voice_directsound 79, 0, DirectSoundWaveData_wb_n_brass_max_g4_32, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_wb_choirs_male, keysplit_wb_choirs_male
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 67, 0, DirectSoundWaveData_wb_steel_dr_wb_g4_22, A(127), D(60), S(1), R(116)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup_wb_n_2_kit
	voice_directsound 60, 0, DirectSoundWaveData_wb_clock_n_22, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_wb_minorhit_c3_16, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_wb_synapse_burst_max_22, A(127), D(120), S(127), R(120)
	voice_directsound 48, 0, DirectSoundWaveData_wb_w_noise_32, A(127), D(127), S(127), R(120)

voice_group wb_n_organ
	voice_directsound 60, 0, DirectSoundWaveData_wb_n_organ_c4_32, A(127), D(100), S(110), R(116)
	voice_directsound 77, 0, DirectSoundWaveData_wb_n_organ_f5_32, A(127), D(100), S(110), R(116)

voice_group wb_flute_akai
	voice_directsound 81, 0, DirectSoundWaveData_wb_flute_akai_wb_a5_22, A(127), D(90), S(100), R(118)
	voice_directsound 89, 0, DirectSoundWaveData_wb_flute_akai_wb_f6_22, A(127), D(90), S(100), R(118)

voice_group wb_french_horn
	voice_directsound 53, 0, DirectSoundWaveData_wb_french_horn_f3_32, A(127), D(110), S(120), R(116)
	voice_directsound 62, 0, DirectSoundWaveData_wb_french_horn_d4_32, A(127), D(110), S(120), R(116)

voice_group wb_choirs_male
	voice_directsound 57, 0, DirectSoundWaveData_wb_choirs_male_a3_32, A(127), D(100), S(110), R(118)
	voice_directsound 65, 0, DirectSoundWaveData_wb_choirs_male_f4_32, A(127), D(100), S(110), R(118)
	voice_directsound 72, 0, DirectSoundWaveData_wb_choirs_male_c5_32, A(127), D(100), S(110), R(118)

voice_group wb_n_2_kit, 16
	voice_directsound 45, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 46, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 47, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 48, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 49, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 61, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 62, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 63, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 64, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 58, 64, DirectSoundWaveData_wb_bass_hit01_32, A(127), D(127), S(120), R(116)
	voice_directsound 59, 64, DirectSoundWaveData_wb_bass_hit01_32, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 62, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 63, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 64, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 57, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 58, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 59, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 61, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 62, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 63, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 64, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 65, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 66, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 67, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 68, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 69, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 70, 64, DirectSoundWaveData_wb_eurosne_16, A(127), D(127), S(127), R(127)
	voice_directsound 60, 44, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 60, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 61, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 62, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 63, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 64, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 65, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 66, 44, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_wb_clock_32, A(127), D(127), S(127), R(127)
	voice_directsound 61, 64, DirectSoundWaveData_wb_clock_32, A(127), D(127), S(127), R(127)
	voice_directsound 62, 64, DirectSoundWaveData_wb_clock_32, A(127), D(127), S(127), R(127)
	voice_directsound 63, 64, DirectSoundWaveData_wb_clock_32, A(127), D(127), S(127), R(127)
	voice_directsound 64, 64, DirectSoundWaveData_wb_clock_32, A(127), D(127), S(127), R(127)
	voice_directsound 65, 64, DirectSoundWaveData_wb_clock_32, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 62, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 63, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 64, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 65, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 66, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 67, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 60, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 61, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 62, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 63, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 64, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 65, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 66, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 67, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 60, 14, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
