voice_group test_7
	voice_keysplit voicegroup_test7_harpsichord, keysplit_test7_harpsichord
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 36, 0, DirectSoundWaveData_wb_a_bass_ps_c2_32, A(127), D(60), S(1), R(118)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_keysplit voicegroup_test7_qy70_bass_ld, keysplit_2oct - 20
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 35, 0, DirectSoundWaveData_wb_cool_basE0_22, A(127), D(125), S(120), R(124)
	voice_directsound 30, 0, DirectSoundWaveData_wb_synbass_fs0_32, A(127), D(75), S(1), R(116)
	voice_directsound 61, 0, DirectSoundWaveData_wb_vocoder_you_22, A(127), D(127), S(127), R(120)
	voice_directsound 30, 0, DirectSoundWaveData_wb_vocoder_stop_22, A(127), D(127), S(127), R(120)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 72, 0, DirectSoundWaveData_wb_pbrasslop_c4_max32, A(127), D(127), S(127), R(120)
	voice_directsound 84, 0, DirectSoundWaveData_wb_pbrasslop_c5_max32, A(127), D(127), S(127), R(120)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_keysplit_all voicegroup_test7_kit
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(126), D(127), S(127), R(127)
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, A(125), D(127), S(127), R(120)

voice_group test7_harpsichord
	voice_directsound 57, 0, DirectSoundWaveData_wb_harpsichord_a3_32, A(127), D(60), S(1), R(118)
	voice_directsound 65, 0, DirectSoundWaveData_wb_harpsichord_f4_32, A(127), D(60), S(1), R(118)
	voice_directsound 74, 0, DirectSoundWaveData_wb_harpsichord_d5_32, A(127), D(60), S(1), R(118)

voice_group test7_qy70_bass_ld
	voice_directsound 72, 0, DirectSoundWaveData_wb_europat_max_wb_c4_32, A(127), D(100), S(110), R(124)
	voice_directsound 84, 0, DirectSoundWaveData_wb_europat_max_wb_c5_32, A(127), D(110), S(110), R(124)

voice_group test7_kit, 21
	voice_directsound 50, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 51, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 48, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_wb_cool_snare3_22, A(127), D(127), S(120), R(126)
	voice_directsound 61, 64, DirectSoundWaveData_wb_cool_snare3_22, A(127), D(127), S(120), R(126)
	voice_directsound 62, 64, DirectSoundWaveData_wb_cool_snare3_22, A(127), D(127), S(120), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_wb_bass_hit01_32, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 62, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 63, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 64, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 65, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 62, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 63, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 64, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 65, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 66, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 67, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 68, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 69, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 70, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 71, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 72, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 73, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 74, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 75, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 76, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 77, 64, DirectSoundWaveData_wb_cowbell_max32, A(127), D(127), S(127), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 61, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 62, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 63, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 61, 64, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 62, 64, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 62, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 63, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 64, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 65, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 60, 84, DirectSoundWaveData_wb_splash_cym_32, A(127), D(70), S(0), R(116)
