voice_group test_6
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_keysplit voicegroup_test6_string, keysplit_2oct - 7
	voice_none
	voice_keysplit voicegroup_test6_qy70_bass_ld, keysplit_2oct - 20
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 46, 0, DirectSoundWaveData_wb_timpani2_as_16, A(127), D(80), S(1), R(116)
	voice_directsound 35, 0, DirectSoundWaveData_wb_cool3_basE0_22, A(127), D(125), S(120), R(127)
	voice_none
	voice_directsound 30, 0, DirectSoundWaveData_wb_synbass_fs0_32, A(127), D(75), S(1), R(116)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 72, 0, DirectSoundWaveData_wb_pbrasslop_c4_max32, A(127), D(127), S(127), R(120)
	voice_keysplit voicegroup_test6_dist_gtr, keysplit_2oct - 12
	voice_none
	voice_directsound 48, 0, DirectSoundWaveData_wb_plasma_gt2_c2_32, A(127), D(30), S(1), R(124)
	voice_none
	voice_none
	voice_directsound 60, 0, DirectSoundWaveData_wb_dis_gtl_c3_32, A(127), D(40), S(1), R(124)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 60, 0, DirectSoundWaveData_wb_plasma_gt_c3_32, A(127), D(30), S(1), R(124)
	voice_directsound 72, 0, DirectSoundWaveData_wb_plasma_gt_c4_32, A(127), D(30), S(1), R(124)
	voice_directsound 72, 0, DirectSoundWaveData_wb_plasma_strings2_22, A(127), D(80), S(40), R(116)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_keysplit_all voicegroup_test6_kit
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 72, 0, DirectSoundWaveData_wb_pl_orgloop_c4_32, A(127), D(127), S(127), R(120)
	voice_directsound 72, 0, DirectSoundWaveData_wb_pl_orgloop_c5_32, A(127), D(127), S(127), R(120)
	voice_none
	voice_none
	voice_directsound 60, 0, DirectSoundWaveData_wb_pla_gtl_c3_32, A(127), D(120), S(127), R(120)
	voice_directsound 67, 0, DirectSoundWaveData_wb_pla_gtl_g3_32, A(127), D(120), S(127), R(120)
	voice_directsound 72, 0, DirectSoundWaveData_wb_plasma_gtrif3_22, A(127), D(120), S(127), R(120)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_directsound 36, 0, DirectSoundWaveData_wb_plasma_noise_22, A(127), D(127), S(127), R(124)
	voice_directsound 36, 0, DirectSoundWaveData_wb_plasma_wave_22, A(127), D(127), S(127), R(124)

voice_group test6_string
	voice_directsound 60, 0, DirectSoundWaveData_wb_strings_c4_32, A(127), D(100), S(110), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_wb_strings_a4_32, A(127), D(100), S(110), R(116)

voice_group test6_qy70_bass_ld
	voice_directsound 72, 0, DirectSoundWaveData_wb_europat_max_wb_c4_32, A(127), D(100), S(110), R(126)
	voice_directsound 84, 0, DirectSoundWaveData_wb_europat_max_wb_c5_32, A(127), D(110), S(110), R(126)

voice_group test6_dist_gtr
	voice_directsound 60, 0, DirectSoundWaveData_wb_dis_gtl_c3_32, A(127), D(30), S(1), R(126)
	voice_directsound 72, 0, DirectSoundWaveData_wb_dis_gtl_c4_32, A(127), D(30), S(1), R(126)

voice_group test6_kit, 21
	voice_directsound 50, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(124)
	voice_directsound 51, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(124)
	voice_directsound 48, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_cool_snare2_22, A(127), D(120), S(120), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_cool_snare3_22, A(127), D(127), S(120), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_wb_cool_snare3_22, A(127), D(127), S(120), R(124)
	voice_directsound 62, 64, DirectSoundWaveData_wb_cool_snare3_22, A(127), D(127), S(120), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_bass_hit01_32, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 62, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 63, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 64, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 65, 64, DirectSoundWaveData_wb_bass_ana01_32, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 62, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 63, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 64, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 65, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 66, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 67, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 68, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 69, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 70, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 71, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 72, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 73, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 74, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 75, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 76, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 77, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 78, 64, DirectSoundWaveData_wb_synth_snaer02_32, A(127), D(127), S(127), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 62, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 63, 64, DirectSoundWaveData_wb_dance_close_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 62, 64, DirectSoundWaveData_wb_dance_open_hat_32, A(127), D(127), S(127), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 62, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 60, 20, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 61, 20, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 62, 20, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 60, 84, DirectSoundWaveData_wb_splash_cym_32, A(127), D(70), S(0), R(116)
	voice_directsound 60, 100, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 61, 100, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 62, 100, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 63, 100, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 64, 100, DirectSoundWaveData_wb_chinese_cym_32, A(127), D(80), S(0), R(110)
	voice_directsound 60, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 62, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 63, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 64, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 65, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 66, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 67, 64, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 60, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 61, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 62, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 63, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 64, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 65, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 66, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 67, 114, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
	voice_directsound 60, 14, DirectSoundWaveData_wb_crash_cym_32, A(127), D(90), S(0), R(114)
