	.align 2
voicegroup336::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_dance_drums_kick, 255, 0, 255, 178						@ 127/127/127/120/ 64
	voice_directsound 61, 64, DirectSoundWaveData_dp_dance_drums_kick, 255, 0, 255, 178						@ 127/127/127/120/ 64
	voice_directsound 62, 64, DirectSoundWaveData_dp_dance_drums_kick, 255, 0, 255, 178						@ 127/127/127/120/ 64
	voice_directsound 63, 64, DirectSoundWaveData_dp_dance_drums_kick, 255, 0, 255, 178						@ 127/127/127/120/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_sd90_power2_snare, 255, 225, 127, 208					@ 127/114/ 90/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_b2_halion_t9_analog_kick, 255, 0, 255, 88					@ 127/127/127/124/ 64
	voice_directsound 61, 64, DirectSoundWaveData_b2_halion_t9_analog_kick, 255, 0, 255, 88					@ 127/127/127/124/ 64
	voice_directsound 60, 64, DirectSoundWaveData_b2_halionone_t9_analog_snare, 255, 0, 227, 197			@ 127/127/120/118/ 64
	voice_directsound 60, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_closed, 255, 0, 255, 197	@ 127/127/127/118/100
	voice_directsound 60, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 61, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 62, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 63, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 64, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 65, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 66, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 67, 100, DirectSoundWaveData_b2_halionone_t9_analog_hihat_open, 255, 0, 255, 178		@ 127/127/127/120/100
	voice_directsound 60, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 64, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 65, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 66, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 67, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 68, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 69, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 70, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 71, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 72, 64, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/ 64
	voice_directsound 60, 20, DirectSoundWaveData_bw_battery3_chinese_cymbal, 255, 249, 0, 225				@ 127/ 80/  0/110/ 20
	voice_directsound 60, 20, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/ 20
	voice_directsound 60, 100, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/100
	voice_directsound 60, 100, DirectSoundWaveData_bw_battery3_chinese_cymbal, 255, 249, 0, 225				@ 127/ 80/  0/110/100
	voice_directsound 63, 84, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/ 84
	voice_directsound 64, 44, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216				@ 127/ 90/  0/114/ 44
