	.align 2
voicegroup192::
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_037, 255, 0, 255, 188
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_005, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_027, 22, 188, 206, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_027, 255, 188, 206, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_028, 255, 245, 0, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_027, 255, 188, 206, 115
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_043, 64, 204, 154, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_044, 255, 165, 206, 188
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_051, 255, 216, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_052, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_053, 255, 188, 154, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_034, 64, 0, 0, 165
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 2
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 2
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_030, 255, 226, 103, 188
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_044, 255, 188, 180, 188
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_027, 255, 188, 206, 226
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_043, 255, 204, 154, 204
