	.align 2
voicegroup191::
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_000, 64, 165, 206, 226
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_001, 64, 204, 103, 188
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_002, 64, 242, 51, 216
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_000, 64, 235, 25, 239
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_003, 51, 188, 206, 226
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_000, 255, 188, 77, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_004, 255, 0, 255, 149
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_005, 255, 165, 154, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_006, 255, 249, 25, 204
	voice_keysplit voicegroup200, KeySplitTable_pmd1_6
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_002, 255, 242, 128, 216
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_009, 255, 0, 255, 127
	voice_keysplit voicegroup199, KeySplitTable_pmd1_5
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_012, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_013, 128, 235, 255, 242
	voice_keysplit voicegroup203, KeySplitTable_pmd1_6
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_014, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_014, 51, 216, 128, 149
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_015, 255, 0, 255, 127
	voice_keysplit voicegroup194, KeySplitTable_pmd1_1
	voice_keysplit voicegroup201, KeySplitTable_pmd1_0
	voice_keysplit voicegroup195, KeySplitTable_pmd1_1
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_043, 15, 0, 255, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_044, 19, 165, 206, 216
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_032, 37, 0, 255, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_000, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_001, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_002, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_003, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_004, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_005, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_006, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_007, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_008, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_009, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_010, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_011, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_012, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_013, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_014, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_015, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_005, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_031, 255, 216, 128, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_033, 255, 188, 103, 165
	voice_keysplit voicegroup205, KeySplitTable_pmd1_7
	voice_keysplit voicegroup196, KeySplitTable_pmd1_2
	voice_keysplit voicegroup197, KeySplitTable_pmd1_3
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_033, 255, 188, 103, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_006, 255, 249, 25, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_033, 255, 188, 103, 216
	voice_keysplit voicegroup202, KeySplitTable_pmd1_5
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_035, 255, 235, 180, 188
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5
	voice_square_2_alt 60, 0, 0, 0, 2, 3, 5
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 3, 5
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 3
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_030, 255, 165, 154, 149
	voice_square_2_alt 60, 0, 2, 2, 0, 7, 4
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 7, 4
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 7, 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_012, 0, 0, 15, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_000, 0, 0, 15, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_001, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_002, 0, 0, 15, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_002, 0, 0, 15, 4
	voice_square_2_alt 60, 0, 1, 0, 0, 7, 3
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 7, 3
	voice_keysplit voicegroup206, KeySplitTable_pmd1_2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_001, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 5
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 5
	voice_keysplit voicegroup198, KeySplitTable_pmd1_4
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 3
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 5
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 5
	voice_square_2_alt 60, 0, 2, 2, 0, 7, 3
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 7, 3
	voice_square_2_alt 60, 0, 2, 1, 1, 15, 3
	voice_square_1_alt 60, 0, 0, 2, 1, 1, 15, 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_016, 2, 0, 15, 2
	voice_square_1_alt 60, 0, 0, 1, 1, 1, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 1, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_016, 0, 0, 15, 2
