voice_group voicegroup191
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Piano_2_______, keysplit_4oct - 8
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_E_Piano_1___8P, keysplit_3oct + 1
	voice_directsound 62, 0, DirectSoundWaveData_E_Piano_2___881, 255, 253, 0, 127
	voice_keysplit voicegroup_Harpsichord___, keysplit_3oct + 4
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Music_Box_____1, 255, 249, 0, 240
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Marimba_____88, keysplit_2oct - 6
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Tubular_bell__1, 255, 246, 0, 244
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Accordion_It8P, keysplit_3oct - 9
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Bandoneon___8P, keysplit_3oct + 2
	voice_keysplit voicegroup_Nylon_str_Gt8P, keysplit_2oct + 1
	voice_keysplit voicegroup_Steel_str_Gt8P, keysplit_2oct - 1
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Acoustic_Bs___, keysplit_2oct + 14
	voice_keysplit voicegroup_Fingered_Bs_8P, keysplit_2oct + 23
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Viola_______8P, keysplit_2oct - 8
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_PizzicatoStr88, keysplit_4oct - 4
	voice_keysplit voicegroup_Harp________88, keysplit_4oct - 8
	voice_directsound 60, 0, DirectSoundWaveData_Timpani_____881, 255, 244, 0, 241
	voice_keysplit voicegroup_Strings_______, keysplit_3oct + 1
	voice_keysplit voicegroup_Slow_Strings__, keysplit_3oct + 1
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Choir_Aahs__8P, keysplit_2oct - 1
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Trumpet_______1, 255, 254, 233, 163
	voice_keysplit voicegroup_Trombone______, keysplit_2oct - 1
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_French_Horns881, 255, 254, 183, 212
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_Oboe__________, keysplit_2oct - 18
	voice_directsound 60, 0, DirectSoundWaveData_EnglishHorn_881, 255, 254, 160, 127
	voice_directsound 60, 0, DirectSoundWaveData_Bassoon_____881, 255, 254, 166, 127
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Piccolo_____881, 255, 253, 150, 127
	voice_keysplit voicegroup_Flute_2_____8P, keysplit_2oct - 18
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Whistle_____551, 255, 0, 255, 127
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Atmosphere__551, 255, 245, 114, 235
	voice_directsound 60, 0, DirectSoundWaveData_Brightness__551, 255, 251, 31, 242
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_Kalimba_____8P1, 255, 248, 0, 221
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_DR__LowW_Blk, 255, 0, 255, 200
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit voicegroup_European_Pf_8P, keysplit_6oct - 5
	voice_keysplit_all voicegroup_STANDARD_1____

@voice_group Piano_1_______ @ 4oct - 4
@	voice_directsound 60, 0, DirectSoundWaveData_Piano_1_______1, 255, 253, 0, 221
@	voice_directsound 60, 0, DirectSoundWaveData_Piano_1_______2, 255, 248, 0, 211
@	voice_directsound 60, 0, DirectSoundWaveData_Piano_1_______3, 255, 248, 0, 203
@	voice_directsound 60, 0, DirectSoundWaveData_Piano_1_______4, 255, 239, 0, 200

voice_group European_Pf_8P @ 6oct - 5
	voice_directsound 62, 0, DirectSoundWaveData_European_Pf_8P1, 255, 252, 0, 227
	voice_directsound 62, 0, DirectSoundWaveData_European_Pf_8P2, 255, 252, 0, 221
	voice_directsound 62, 0, DirectSoundWaveData_European_Pf_8P3, 255, 248, 0, 211
	voice_directsound 62, 0, DirectSoundWaveData_European_Pf_8P4, 255, 246, 0, 206
	voice_directsound 62, 0, DirectSoundWaveData_European_Pf_8P5, 255, 245, 0, 190
	voice_directsound 62, 0, DirectSoundWaveData_European_Pf_8P6, 255, 242, 0, 214

voice_group Piano_2_______ @ 4oct - 8
	voice_directsound 60, 0, DirectSoundWaveData_Piano_2_______1, 255, 252, 0, 212
	voice_directsound 60, 0, DirectSoundWaveData_Piano_2_______2, 255, 247, 0, 214
	voice_directsound 60, 0, DirectSoundWaveData_Piano_2_______3, 255, 247, 0, 218
	voice_directsound 60, 0, DirectSoundWaveData_Piano_2_______4, 255, 241, 0, 210

voice_group E_Piano_1___8P @ 3oct + 1
	voice_directsound 60, 0, DirectSoundWaveData_E_Piano_1___8P1, 255, 250, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_E_Piano_1___8P2, 255, 251, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_E_Piano_1___8P3, 255, 249, 0, 127

voice_group Harpsichord___ @ 3oct + 4
	voice_directsound 60, 0, DirectSoundWaveData_Harpsichord___1, 255, 249, 0, 160
	voice_directsound 60, 0, DirectSoundWaveData_Harpsichord___2, 255, 247, 0, 160
	voice_directsound 60, 0, DirectSoundWaveData_Harpsichord___3, 255, 244, 0, 160

voice_group Marimba_____88 @ 2oct - 6
	voice_directsound 60, 0, DirectSoundWaveData_Marimba_____881, 255, 233, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_Marimba_____882, 255, 239, 0, 216

@voice_group Accordion_Fr8P @ 3oct + 2
@	voice_directsound 60, 0, DirectSoundWaveData_Accordion_Fr8P1, 255, 250, 160, 127
@	voice_directsound 60, 0, DirectSoundWaveData_Accordion_Fr8P2, 255, 250, 180, 127
@	voice_directsound 60, 0, DirectSoundWaveData_Accordion_Fr8P3, 255, 250, 200, 127

voice_group Accordion_It8P @ 3oct - 9
	voice_directsound 60, 0, DirectSoundWaveData_Accordion_It8P1, 255, 250, 200, 127
	voice_directsound 60, 0, DirectSoundWaveData_Accordion_It8P2, 255, 250, 200, 127
	voice_directsound 60, 0, DirectSoundWaveData_Accordion_It8P3, 255, 250, 200, 127

voice_group Bandoneon___8P @ 3oct + 2
	voice_directsound 60, 0, DirectSoundWaveData_Bandoneon___8P1, 255, 254, 204, 127
	voice_directsound 60, 0, DirectSoundWaveData_Bandoneon___8P2, 255, 253, 162, 127
	voice_directsound 60, 0, DirectSoundWaveData_Bandoneon___8P3, 255, 253, 174, 127

voice_group Nylon_str_Gt8P @ 2oct + 1
	voice_directsound 60, 0, DirectSoundWaveData_Nylon_str_Gt8P1, 255, 252, 0, 180
	voice_directsound 60, 0, DirectSoundWaveData_Nylon_str_Gt8P2, 255, 252, 0, 180

voice_group Steel_str_Gt8P @ 2oct - 1
	voice_directsound 60, 0, DirectSoundWaveData_Steel_str_Gt8P1, 255, 251, 0, 180
	voice_directsound 60, 0, DirectSoundWaveData_Steel_str_Gt8P2, 255, 250, 0, 180

voice_group Acoustic_Bs___ @ 2oct + 14
	voice_directsound 60, 0, DirectSoundWaveData_Acoustic_Bs___1, 255, 250, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_Acoustic_Bs___2, 255, 247, 0, 127

voice_group Fingered_Bs_8P @ 2oct + 23
	voice_directsound 62, 0, DirectSoundWaveData_Fingered_Bs_8P1, 255, 252, 68, 127
	voice_directsound 62, 0, DirectSoundWaveData_Fingered_Bs_8P2, 255, 252, 68, 127

voice_group Viola_______8P @ 2oct - 8
	voice_directsound 60, 0, DirectSoundWaveData_Viola_______8P1, 255, 0, 255, 189
	voice_directsound 60, 0, DirectSoundWaveData_Viola_______8P2, 255, 0, 255, 189

voice_group PizzicatoStr88 @ 4oct - 4
	voice_directsound 60, 0, DirectSoundWaveData_PizzicatoStr881, 255, 235, 0, 222
	voice_directsound 60, 0, DirectSoundWaveData_PizzicatoStr882, 255, 228, 0, 229
	voice_directsound 60, 0, DirectSoundWaveData_PizzicatoStr883, 255, 225, 0, 191
	voice_directsound 60, 0, DirectSoundWaveData_PizzicatoStr884, 255, 223, 0, 190

voice_group Harp________88 @ 4oct - 8
	voice_directsound 62, 0, DirectSoundWaveData_Harp________881, 255, 249, 0, 233
	voice_directsound 62, 0, DirectSoundWaveData_Harp________882, 255, 247, 0, 233
	voice_directsound 62, 0, DirectSoundWaveData_Harp________883, 255, 249, 0, 233
	voice_directsound 62, 0, DirectSoundWaveData_Harp________884, 255, 247, 0, 233

voice_group Strings_______ @ 3oct + 1
	voice_directsound 62, 0, DirectSoundWaveData_Strings_______1, 128, 255, 180, 223
	voice_directsound 62, 0, DirectSoundWaveData_Strings_______2, 128, 255, 180, 223
	voice_directsound 62, 0, DirectSoundWaveData_Strings_______3, 128, 255, 180, 223

voice_group Slow_Strings__ @ 3oct + 1
	voice_directsound 60, 0, DirectSoundWaveData_Strings_______1, 20, 255, 230, 235
	voice_directsound 60, 0, DirectSoundWaveData_Strings_______2, 20, 255, 230, 235
	voice_directsound 60, 0, DirectSoundWaveData_Strings_______3, 20, 255, 230, 235

voice_group Choir_Aahs__8P @ 2oct - 1
	voice_directsound 60, 0, DirectSoundWaveData_Choir_Aahs__8P1, 30, 255, 251, 228
	voice_directsound 60, 0, DirectSoundWaveData_Choir_Aahs__8P2, 30, 255, 203, 228

voice_group Trombone______ @ 2oct - 1
	voice_directsound 60, 0, DirectSoundWaveData_Trombone______1, 255, 255, 233, 163
	voice_directsound 60, 0, DirectSoundWaveData_Trombone______2, 255, 255, 233, 163

voice_group Oboe__________ @ 2oct - 18
	voice_directsound 60, 0, DirectSoundWaveData_Oboe__________1, 255, 255, 202, 127
	voice_directsound 60, 0, DirectSoundWaveData_Oboe__________2, 255, 255, 179, 127

@	voice_directsound 60, 0, DirectSoundWaveData_Flute_______881, 255, 253, 200, 127

voice_group Flute_2_____8P @ 2oct - 18
	voice_directsound 60, 0, DirectSoundWaveData_Flute_2_____8P1, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_Flute_2_____8P2, 255, 251, 235, 127

voice_group STANDARD_1____
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_K1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_K2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_K1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_K2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR55Kick_1__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR55Kick_2__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_K1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_K2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_K1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_K2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_K1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_K2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_K2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_K1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88808_BD__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88909_BD__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Dance_K_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PVoice_1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PVoice_2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PVoice_3_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_K2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_K1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__MC_Beep1, 255, 0, 255, 50
	voice_directsound 72, 64, DirectSoundWaveData_DR__MC_Beep1, 255, 0, 255, 50
	voice_directsound 60, 64, DirectSoundWaveData_DR__CncrtSnr, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Snr_Roll, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__FingSnp2, 255, 0, 255, 200
	voice_directsound 60, 49, DirectSoundWaveData_DR__High_Q__, 255, 0, 255, 200
	voice_directsound 60, 49, DirectSoundWaveData_DR__Slap____, 255, 0, 255, 200
	voice_directsound 60, 54, DirectSoundWaveData_DR__Scr_Push, 255, 0, 255, 200
	voice_directsound 60, 54, DirectSoundWaveData_DR__Scr_Pull, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Sticks__, 255, 0, 255, 200
	voice_directsound 60, 54, DirectSoundWaveData_DR__Sq_Click, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Mt_Click, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Mt__Bell, 255, 237, 0, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_K2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_K1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Sd_Stick, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_S1_, 255, 0, 255, 200
	voice_directsound 60, 54, DirectSoundWaveData_DR__909_Clap, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_S2_, 255, 0, 255, 200
	voice_directsound 57, 34, DirectSoundWaveData_DR__LowTom_1, 255, 247, 0, 200
	voice_directsound 48, 84, DirectSoundWaveData_DR__C_Hi_Hat, 255, 0, 255, 200
	voice_directsound 60, 46, DirectSoundWaveData_DR__LowTom_1, 255, 246, 0, 200
	voice_directsound 48, 84, DirectSoundWaveData_DR__P_Hi_Hat, 255, 0, 255, 200
	voice_directsound 57, 58, DirectSoundWaveData_DR__MidTom_1, 255, 245, 0, 200
	voice_directsound 48, 84, DirectSoundWaveData_DR__O_Hi_Hat, 255, 233, 0, 200
	voice_directsound 60, 70, DirectSoundWaveData_DR__MidTom_1, 255, 244, 0, 200
	voice_directsound 57, 82, DirectSoundWaveData_DR__Hi_Tom_1, 255, 243, 0, 200
	voice_directsound 60, 84, DirectSoundWaveData_DR__CrshCym1, 255, 247, 0, 224
	voice_directsound 60, 94, DirectSoundWaveData_DR__Hi_Tom_1, 255, 242, 0, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__RideCym1, 255, 252, 0, 224
	voice_directsound 60, 44, DirectSoundWaveData_DR__Chin_Cym, 255, 244, 0, 224
	voice_directsound 60, 44, DirectSoundWaveData_DR__RideBell, 255, 248, 0, 224
	voice_directsound 60, 74, DirectSoundWaveData_DR__Tambourn, 255, 0, 255, 200
	voice_directsound 60, 54, DirectSoundWaveData_DR__SplshCym, 255, 239, 0, 224
	voice_directsound 60, 84, DirectSoundWaveData_DR__Cowbell_, 255, 0, 255, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__CrshCym2, 255, 246, 0, 224
	voice_directsound 60, 29, DirectSoundWaveData_DR__Vib_slap, 255, 242, 0, 224
	voice_directsound 60, 44, DirectSoundWaveData_DR__RideCym2, 255, 249, 0, 224
	voice_directsound 60, 99, DirectSoundWaveData_DR__Hi_Bongo, 255, 0, 255, 200
	voice_directsound 60, 99, DirectSoundWaveData_DR__LowBongo, 255, 0, 255, 200
	voice_directsound 60, 39, DirectSoundWaveData_DR__MH_Conga, 255, 0, 255, 200
	voice_directsound 60, 39, DirectSoundWaveData_DR__OH_Conga, 255, 0, 255, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__LowConga, 255, 233, 0, 200
	voice_directsound 60, 84, DirectSoundWaveData_DR__Hi_Timbl, 255, 0, 255, 200
	voice_directsound 60, 84, DirectSoundWaveData_DR__LowTimbl, 255, 0, 255, 200
	voice_directsound 65, 29, DirectSoundWaveData_DR__LowAgogo, 255, 0, 255, 200
	voice_directsound 60, 29, DirectSoundWaveData_DR__LowAgogo, 255, 0, 255, 200
	voice_directsound 60, 29, DirectSoundWaveData_DR__Cabasa__, 255, 0, 255, 200
	voice_directsound 60, 24, DirectSoundWaveData_DR__Maracas_, 255, 0, 255, 200
	voice_directsound 62, 99, DirectSoundWaveData_DR__LL_Whisl, 255, 0, 255, 200
	voice_directsound 60, 99, DirectSoundWaveData_DR__LL_Whisl, 255, 0, 255, 200
	voice_directsound 60, 94, DirectSoundWaveData_DR__S_Guiro_, 255, 0, 255, 200
	voice_directsound 60, 94, DirectSoundWaveData_DR__L_Guiro_, 255, 0, 255, 200
	voice_directsound 60, 84, DirectSoundWaveData_DR__Claves__, 255, 0, 255, 200
	voice_directsound 68, 99, DirectSoundWaveData_DR__LowW_Blk, 255, 0, 255, 200
	voice_directsound 63, 99, DirectSoundWaveData_DR__LowW_Blk, 255, 0, 255, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__Mt_Cuica, 255, 0, 255, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__Op_Cuica, 255, 0, 255, 200
	voice_directsound 60, 24, DirectSoundWaveData_DR__Mt_Trigl, 255, 0, 255, 200
	voice_directsound 60, 24, DirectSoundWaveData_DR__Op_Trigl, 255, 241, 0, 200
	voice_directsound 60, 94, DirectSoundWaveData_DR__Shaker__, 255, 0, 255, 200
	voice_directsound 60, 99, DirectSoundWaveData_DR__Jng_Bell, 255, 0, 255, 200
	voice_directsound 60, 104, DirectSoundWaveData_DR__BellTree, 255, 240, 0, 224
	voice_directsound 60, 34, DirectSoundWaveData_DR__Castanet, 255, 0, 255, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__Mt_Surdo, 255, 0, 255, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__Op_Surdo, 255, 239, 0, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Applaus2, 7, 0, 255, 237
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_S1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_S2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_S1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_S2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_S1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_S2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR55Snare_2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PStd_1_S1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PStd_1_S2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PStd_1_S3, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_S1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_S2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_S1_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_S2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_S1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_S2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR55Gated_SD, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Dance_S1, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Dance_S2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Disco_S_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_S2_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR55Elec_SD_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_S3_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8P707_S1__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88808_S1__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88808_S2__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88909_S1__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88909_S2__, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PRapSnare, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PJungleS1, 255, 0, 255, 200
	voice_directsound 55, 64, DirectSoundWaveData_DR8PHouse_S2, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR88House_S_, 255, 0, 255, 200
	voice_directsound 60, 64, DirectSoundWaveData_DR8PHouse_S2, 255, 0, 255, 200
