	.align 2
voicegroup355:: @ 
	voice_keysplit voicegroup323, KeySplitTable116   @ piano 1
	voice_keysplit voicegroup237, KeySplitTable83    @ rhodes 2 (hgss)
	voice_keysplit voicegroup235, KeySplitTable91    @ piano octave
	voice_keysplit voicegroup294, KeySplitTable36    @ rhodes
	voice_keysplit voicegroup300, KeySplitTable36    @ rhodes (short release)
	voice_keysplit voicegroup234, KeySplitTable36    @ piano 2
	voice_keysplit voicegroup290, KeySplitTable70    @ harpsichord
	voice_keysplit voicegroup332, KeySplitTable114   @ piano 1 (longer decay)
	voice_keysplit voicegroup341, KeySplitTable120   @ piano 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup297, KeySplitTable76    @ vibraphone
	voice_keysplit voicegroup295, KeySplitTable74    @ marimba
	voice_keysplit voicegroup240, KeySplitTable115   @ xylophone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup241, KeySplitTable25    @ tubular bell
	voice_directsound 60, 0, DirectSoundWaveData_bw_074glocknc5, 255, 249, 0, 205
	voice_keysplit voicegroup243, KeySplitTable76    @ music box
	voice_keysplit voicegroup244, KeySplitTable71    @ drawbar organ
	voice_keysplit voicegroup245, KeySplitTable71    @ jazz organ
	voice_keysplit voicegroup291, KeySplitTable71    @ accordion
	voice_keysplit voicegroup292, KeySplitTable72    @ nylon str. guitar
	voice_keysplit voicegroup351, KeySplitTable127   @ spanish guitar
	voice_keysplit voicegroup250, KeySplitTable32    @ distortion guitar 2 (hgss)
	voice_keysplit voicegroup342, KeySplitTable41    @ jazz guitar
	voice_keysplit voicegroup316, KeySplitTable41    @ clean guitar
	voice_keysplit voicegroup252, KeySplitTable42    @ upright bass
	voice_keysplit voicegroup253, KeySplitTable43    @ fingered bass
	voice_keysplit voicegroup311, KeySplitTable86    @ fretless bass
	voice_keysplit voicegroup309, KeySplitTable117   @ slap bass
	voice_keysplit voicegroup254, KeySplitTable73    @ synth bass
	voice_keysplit voicegroup255, KeySplitTable60    @ strings 1
	voice_keysplit voicegroup298, KeySplitTable82    @ strings 2
	voice_keysplit voicegroup256, KeySplitTable46    @ violin
	voice_keysplit voicegroup257, KeySplitTable66    @ cello
	voice_keysplit voicegroup293, KeySplitTable48    @ pizzicato
	voice_keysplit voicegroup299, KeySplitTable78    @ harp 1
	voice_keysplit voicegroup302, KeySplitTable80    @ harp 2
	voice_keysplit voicegroup319, KeySplitTable97    @ pipe organ
	voice_keysplit voicegroup260, KeySplitTable61    @ timpani 1
	voice_keysplit voicegroup261, KeySplitTable39    @ trumpets 1
	voice_keysplit voicegroup262, KeySplitTable47    @ trombones
	voice_keysplit voicegroup327, KeySplitTable72    @ french horns 1
	voice_keysplit voicegroup327, KeySplitTable41    @ french horns 2
	voice_keysplit voicegroup305, KeySplitTable44    @ tuba
	voice_keysplit voicegroup288, KeySplitTable46    @ oboe
	voice_keysplit voicegroup266, KeySplitTable52    @ clarinet
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_064flt2a5, 255, 246, 159, 205
	voice_keysplit voicegroup328, KeySplitTable65    @ flute 1
	voice_keysplit voicegroup268, KeySplitTable54    @ bassoon
	voice_keysplit voicegroup314, KeySplitTable71    @ alto sax
	voice_keysplit voicegroup312, KeySplitTable87    @ timpani 2
	voice_directsound 60, 0, DirectSoundWaveData_b2_synthbassd2, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_168slapbc2, 255, 197, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_synthbassfs1_plasma, 255, 249, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchhitas2_leader, 255, 248, 0, 205
	voice_keysplit voicegroup261, KeySplitTable112   @ trumpets 2
	voice_keysplit voicegroup262, KeySplitTable27    @ trombones 2
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerchord_n, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_guitarchug_n, 255, 253, 0, 171
	voice_keysplit voicegroup327, KeySplitTable68    @ french horns 3
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 0, 255, 205
	voice_keysplit voicegroup303, KeySplitTable81    @ choir 1
	voice_keysplit voicegroup344, KeySplitTable121   @ synth vox
	voice_keysplit voicegroup324, KeySplitTable62    @ choir 2
	voice_keysplit voicegroup353, KeySplitTable129   @ choir 3
	voice_keysplit voicegroup349, KeySplitTable76    @ synth lead (humilau)
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar1, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar2, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar3, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_bw_guitarbendc5_plasma, 255, 197, 255, 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_guitarfeedbackcs5, 255, 197, 255, 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_acidbassb1short, 255, 42, 227, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_fhornsripc3, 255, 248, 0, 205
	voice_keysplit voicegroup330, KeySplitTable108   @ sitar
	voice_directsound 60, 0, DirectSoundWaveData_bw_steeldrumc4_undella, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_hardbasse2, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_hardbasse3, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_recorderg5, 255, 42, 227, 129
	voice_keysplit_all voicegroup337				 @ drum set 2
	voice_keysplit_all voicegroup336				 @ drum set 1
	voice_keysplit_all voicegroup338				 @ drum set 3 (addictive drums)
	voice_keysplit voicegroup244, KeySplitTable102   @ drawbar organ alt
	voice_directsound 60, 0, DirectSoundWaveData_bw_solotrumpetc5, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_trombonesstaccatocs2, 255, 42, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_spiccatostringse2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_trumpetsstaccatogs4_loop, 255, 0, 255, 224
	voice_directsound 60, 0, DirectSoundWaveData_hg_021cellog2, 254, 242, 255, 205
	voice_keysplit voicegroup343, KeySplitTable65    @ pan flute
	voice_keysplit voicegroup352, KeySplitTable128   @ gamelan
	voice_keysplit voicegroup340, KeySplitTable118   @ pink strat
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrate3, 255, 253, 0, 171
	voice_keysplit voicegroup289, KeySplitTable39    @ trumpets (short start)
	voice_keysplit voicegroup347, KeySplitTable123   @ square lead
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_doublsawc5, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_reversecymbale2, 255, 0, 255, 236
	voice_directsound 60, 0, DirectSoundWaveData_b2_gongf, 255, 251, 0, 205
	voice_keysplit voicegroup350, KeySplitTable123   @ dj handy
	voice_square_2 60, 0, 2, 0, 7, 2, 0
	voice_square_1 60, 0, 0, 2, 0, 7, 2, 0
	voice_keysplit voicegroup220, KeySplitTable30    @ trombone (DPPt)
	voice_directsound 60, 0, DirectSoundWaveData_bw_sawleadc4_vsleader, 255, 242, 191, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_synthbassf1_leader, 255, 251, 14, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_slapbassc2_marinetube, 255, 42, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_suspensestringsc4, 255, 242, 191, 129
	voice_directsound 60, 0, DirectSoundWaveData_b2_wind_grotto, 255, 197, 255, 0
	voice_keysplit voicegroup348, KeySplitTable126   @ over run
	voice_keysplit voicegroup255, KeySplitTable79    @ strings 1 alt
	voice_directsound 60, 0, DirectSoundWaveData_hg_096flt1c6, 255, 246, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_nimbasagymsynthe1, 255, 242, 227, 214
	voice_directsound 60, 0, DirectSoundWaveData_b2_nimbasagymsynthe4, 255, 242, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_nimbasagymsynthe6, 255, 242, 227, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
