	.align 2
voicegroup350:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_b2_djhandyd2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_djhandyd3, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_djhandyd4, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_djhandyd5, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_djhandyd6, 255, 0, 255, 171
