	.align 2
voicegroup297::
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_40, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_52, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_64, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_69, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_81, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
