	.align 2
voicegroup341::
	voice_directsound 60, 0, DirectSoundWaveData_b2_pianof1, 255, 251, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_b2_pianof2, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_pianof3, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_pianof4, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_pianof5, 255, 251, 0, 205
