	.align 2
voicegroup191::
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_directsound 60, 0, DirectSoundWaveData_88Timpani_____1, 255, 244, 2, 241
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit __Piano_1_____, KeySplitTable_4oct - 5
	voice_keysplit_all __STANDARD_1__

__Piano_1_____::
	voice_directsound 60, 0, DirectSoundWaveData___Piano_1_____1, 255, 253, 70, 221
	voice_directsound 60, 0, DirectSoundWaveData___Piano_1_____2, 255, 248, 19, 211
	voice_directsound 60, 0, DirectSoundWaveData___Piano_1_____3, 255, 248, 15, 203
	voice_directsound 60, 0, DirectSoundWaveData___Piano_1_____4, 255, 239, 4, 200

__STANDARD_1__::
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_K1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_K2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_K1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_K2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR55Kick_1__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR55Kick_2__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_K1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_K2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_K1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_K2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_K1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_K2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_K2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_K1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88808_BD__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88909_BD__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Dance_K_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PVoice_1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PVoice_2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PVoice_3_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_K2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_K1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__MC_Beep1, 255, 0, 255, 50
	voice_directsound 72, 64, DirectSoundWaveData_DR__MC_Beep1, 255, 0, 255, 50
	voice_directsound 60, 64, DirectSoundWaveData_DR__CncrtSnr, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Snr_Roll, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__FingSnp2, 255, 0, 255, 127
	voice_directsound 60, 49, DirectSoundWaveData_DR__High_Q__, 255, 0, 255, 127
	voice_directsound 60, 49, DirectSoundWaveData_DR__Slap____, 255, 0, 255, 127
	voice_directsound 60, 54, DirectSoundWaveData_DR__Scr_Push, 255, 0, 255, 127
	voice_directsound 60, 54, DirectSoundWaveData_DR__Scr_Pull, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Sticks__, 255, 0, 255, 127
	voice_directsound 60, 54, DirectSoundWaveData_DR__Sq_Click, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Mt_Click, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Mt__Bell, 255, 237, 0, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_K2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_K1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Sd_Stick, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_S1_, 255, 0, 255, 127
	voice_directsound 60, 54, DirectSoundWaveData_DR__909_Clap, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Std1_S2_, 255, 0, 255, 127
	voice_directsound 57, 34, DirectSoundWaveData_DR__LowTom_1, 255, 247, 0, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__C_Hi_Hat, 255, 0, 255, 127
	voice_directsound 60, 46, DirectSoundWaveData_DR__LowTom_1, 255, 246, 0, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__P_Hi_Hat, 255, 0, 255, 127
	voice_directsound 57, 58, DirectSoundWaveData_DR__MidTom_1, 255, 245, 0, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__O_Hi_Hat, 255, 233, 0, 127
	voice_directsound 60, 70, DirectSoundWaveData_DR__MidTom_1, 255, 244, 0, 127
	voice_directsound 57, 82, DirectSoundWaveData_DR__Hi_Tom_1, 255, 243, 0, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__CrshCym1, 255, 247, 0, 200
	voice_directsound 60, 94, DirectSoundWaveData_DR__Hi_Tom_1, 255, 242, 0, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__RideCym1, 255, 252, 0, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__Chin_Cym, 255, 244, 0, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__RideBell, 255, 248, 0, 200
	voice_directsound 60, 74, DirectSoundWaveData_DR__Tambourn, 255, 0, 255, 127
	voice_directsound 60, 54, DirectSoundWaveData_DR__SplshCym, 255, 239, 0, 200
	voice_directsound 60, 84, DirectSoundWaveData_DR__Cowbell_, 255, 0, 255, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__CrshCym2, 255, 246, 0, 200
	voice_directsound 60, 29, DirectSoundWaveData_DR__Vib_slap, 255, 242, 0, 200
	voice_directsound 60, 44, DirectSoundWaveData_DR__RideCym2, 255, 249, 0, 200
	voice_directsound 60, 99, DirectSoundWaveData_DR__Hi_Bongo, 255, 0, 255, 127
	voice_directsound 60, 99, DirectSoundWaveData_DR__LowBongo, 255, 0, 255, 127
	voice_directsound 60, 39, DirectSoundWaveData_DR__MH_Conga, 255, 0, 255, 127
	voice_directsound 60, 39, DirectSoundWaveData_DR__OH_Conga, 255, 0, 255, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__LowConga, 255, 233, 0, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__Hi_Timbl, 255, 0, 255, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__LowTimbl, 255, 0, 255, 127
	voice_directsound 65, 29, DirectSoundWaveData_DR__LowAgogo, 255, 0, 255, 127
	voice_directsound 60, 29, DirectSoundWaveData_DR__LowAgogo, 255, 0, 255, 127
	voice_directsound 60, 29, DirectSoundWaveData_DR__Cabasa__, 255, 0, 255, 127
	voice_directsound 60, 24, DirectSoundWaveData_DR__Maracas_, 255, 0, 255, 127
	voice_directsound 62, 99, DirectSoundWaveData_DR__LL_Whisl, 255, 0, 255, 127
	voice_directsound 60, 99, DirectSoundWaveData_DR__LL_Whisl, 255, 0, 255, 127
	voice_directsound 60, 94, DirectSoundWaveData_DR__S_Guiro_, 255, 0, 255, 127
	voice_directsound 60, 94, DirectSoundWaveData_DR__L_Guiro_, 255, 0, 255, 127
	voice_directsound 60, 84, DirectSoundWaveData_DR__Claves__, 255, 0, 255, 127
	voice_directsound 65, 99, DirectSoundWaveData_DR__LowW_Blk, 255, 0, 255, 127
	voice_directsound 60, 99, DirectSoundWaveData_DR__LowW_Blk, 255, 0, 255, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__Mt_Cuica, 255, 0, 255, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__Op_Cuica, 255, 0, 255, 127
	voice_directsound 60, 24, DirectSoundWaveData_DR__Mt_Trigl, 255, 0, 255, 127
	voice_directsound 60, 24, DirectSoundWaveData_DR__Op_Trigl, 255, 241, 0, 127
	voice_directsound 60, 94, DirectSoundWaveData_DR__Shaker__, 255, 0, 255, 127
	voice_directsound 60, 99, DirectSoundWaveData_DR__Jng_Bell, 255, 0, 255, 127
	voice_directsound 60, 104, DirectSoundWaveData_DR__BellTree, 255, 240, 0, 200
	voice_directsound 60, 34, DirectSoundWaveData_DR__Castanet, 255, 0, 255, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__Mt_Surdo, 255, 0, 255, 127
	voice_directsound 60, 44, DirectSoundWaveData_DR__Op_Surdo, 255, 239, 0, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Applaus2, 7, 0, 255, 237
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_S1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR__Room_S2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_S1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_1_S2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_S1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Std_2_S2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR55Snare_2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PStd_1_S1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PStd_1_S2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PStd_1_S3, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_S1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Jazz_S2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_S1_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Room_S2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_S1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Power_S2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR55Gated_SD, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Dance_S1, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Dance_S2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Disco_S_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_S2_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR55Elec_SD_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88Elec_S3_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8P707_S1__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88808_S1__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88808_S2__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88909_S1__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88909_S2__, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PRapSnare, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PJungleS1, 255, 0, 255, 127
	voice_directsound 55, 64, DirectSoundWaveData_DR8PHouse_S2, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR88House_S_, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_DR8PHouse_S2, 255, 0, 255, 127
