	.align 2
voicegroup354:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_b2_colressvocal1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_colressvocal2, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_colressvocal3, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_colressvocal4, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_colressvocal5, 255, 0, 255, 0
