	.align 2
voicegroup131FRLGtest::
	voice_keysplit_all voicegroup001
	voice_keysplit_all voicegroup002
	voice_keysplit_all voicegroup176
	voice_keysplit_all voicegroup177
	voice_keysplit_all voicegroup190
	voice_keysplit voicegroup005, KeySplitTable1
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 165, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 165, 180, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 188, 128, 226
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 249, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 180, 108, 209
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 64, 249, 0, 188
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 137, 154, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 188, 103, 165
	voice_directsound 60, 65, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 204, 77, 246
	voice_directsound 60, 65, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 128, 204, 77, 246
	voice_directsound 60, 65, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 85, 204, 77, 246
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 64, 188, 108, 244
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 51, 249, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 204, 51, 242
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 204, 103, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 97, 236
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 76, 133, 137
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 146, 190, 115
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 160, 175, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 160, 123, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 146, 118, 137
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 146, 108, 137
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 127, 103, 201
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 85, 188, 92, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 85, 127, 180, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 64, 188, 128, 201
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 64, 195, 92, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 51, 0, 203, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 37, 165, 103, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 85, 137, 180, 204
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 64, 188, 108, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 37, 127, 77, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 165, 154, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 165, 128, 204
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 204, 92, 226
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 204, 103, 226
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 128, 249, 25, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 85, 165, 154, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 85, 249, 25, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 85, 249, 25, 226
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 64, 195, 103, 220
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 64, 216, 51, 224
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 64, 249, 25, 226
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 51, 204, 92, 226
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 128, 0, 255, 214
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 128, 195, 72, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 165, 154, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 128, 0, 255, 206
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 85, 188, 103, 160
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 64, 204, 113, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 188
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 128, 188, 77, 115
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 226, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 226
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 242
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 0, 193, 76
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 0, 193, 153
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 165, 154, 153
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 165, 154, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 127, 154, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226
	voice_keysplit voicegroup006, KeySplitTable2
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 85, 0, 154, 165
	voice_keysplit voicegroup007, KeySplitTable3
	voice_keysplit voicegroup008, KeySplitTable4
	voice_directsound 60, 0, DirectSoundWaveData_unknown_18, 255, 0, 206, 204
	voice_keysplit voicegroup009, KeySplitTable5
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 209
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 236, 188
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 165, 180, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 175, 154, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 85, 204, 77, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 43, 76, 103, 216
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 12, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 10, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 10, 6
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 9, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 7, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 7, 4
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 6, 3
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 6, 4
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 6, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 4, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 3, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 2, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 2, 2
	voice_square_1_alt 60, 0, 0, 2, 0, 7, 0, 6
	voice_square_1_alt 60, 0, 0, 2, 2, 4, 10, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 10, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 10, 0
	voice_square_1_alt 60, 0, 0, 3, 0, 0, 10, 0
	voice_square_1_alt 60, 0, 0, 3, 0, 1, 9, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 9, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 7, 2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 6, 1
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 6, 2
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 6, 5
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 6, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 3, 5, 2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 5, 2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 4, 1
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 4, 2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 4, 5
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 4, 2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 1
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 4
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 4
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5
	voice_square_1_alt 60, 0, 0, 1, 0, 5, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 1, 2, 3, 1
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 10, 4
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 7, 2
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 7, 5
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 6, 2
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 5, 2
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 5, 2
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 3, 1
	voice_square_1_alt 60, 0, 0, 0, 0, 4, 2, 2
	voice_square_1_alt 60, 0, 0, 0, 0, 5, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 1, 2, 6, 0
	voice_square_1_alt 60, 0, 0, 0, 1, 4, 3, 6
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 12, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 9, 0
	voice_square_2_alt 60, 0, 2, 1, 0, 9, 1
	voice_square_2_alt 60, 0, 2, 0, 2, 7, 1
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 2
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 3
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 5
	voice_square_2_alt 60, 0, 2, 0, 2, 6, 6
	voice_square_2_alt 60, 0, 2, 0, 0, 6, 1
	voice_square_2_alt 60, 0, 2, 0, 2, 5, 5
	voice_square_2_alt 60, 0, 2, 0, 2, 4, 1
	voice_square_2_alt 60, 0, 2, 0, 2, 4, 4
	voice_square_2_alt 60, 0, 2, 0, 2, 3, 1
	voice_square_2_alt 60, 0, 3, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 3, 0, 1, 10, 1
	voice_square_2_alt 60, 0, 1, 0, 1, 10, 2
	voice_square_2_alt 60, 0, 1, 0, 0, 10, 0
	voice_square_2_alt 60, 0, 3, 0, 2, 9, 1
	voice_square_2_alt 60, 0, 3, 0, 1, 9, 0
	voice_square_2_alt 60, 0, 3, 0, 0, 9, 0
	voice_square_2_alt 60, 0, 3, 0, 2, 8, 3
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 2
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3
	voice_square_2_alt 60, 0, 1, 0, 1, 7, 1
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 5
	voice_square_2_alt 60, 0, 1, 0, 1, 7, 5
	voice_square_2_alt 60, 0, 3, 0, 3, 6, 2
	voice_square_2_alt 60, 0, 1, 0, 2, 6, 2
	voice_square_2_alt 60, 0, 3, 0, 2, 6, 3
	voice_square_2_alt 60, 0, 3, 0, 2, 6, 4
	voice_square_2_alt 60, 0, 3, 0, 2, 6, 5
	voice_square_2_alt 60, 0, 3, 0, 1, 6, 3
	voice_square_2_alt 60, 0, 1, 0, 0, 6, 0
	voice_square_2_alt 60, 0, 3, 0, 1, 5, 2
	voice_square_2_alt 60, 0, 3, 0, 4, 4, 4
	voice_square_2_alt 60, 0, 3, 0, 3, 4, 2
	voice_square_2_alt 60, 0, 3, 0, 2, 4, 2
	voice_square_2_alt 60, 0, 1, 0, 2, 4, 2
	voice_square_2_alt 60, 0, 1, 0, 2, 4, 3
	voice_square_2_alt 60, 0, 1, 0, 1, 4, 6
	voice_square_2_alt 60, 0, 3, 0, 3, 3, 0
	voice_square_2_alt 60, 0, 3, 0, 3, 3, 2
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 2
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 4
	voice_square_2_alt 60, 0, 1, 1, 2, 3, 1
	voice_square_2_alt 60, 0, 1, 1, 5, 1, 6
	voice_square_2_alt 60, 0, 3, 2, 4, 10, 0
	voice_square_2_alt 60, 0, 0, 0, 1, 9, 0
	voice_square_2_alt 60, 0, 0, 0, 2, 6, 5
	voice_square_2_alt 60, 0, 0, 0, 5, 0, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 0, 12, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 9, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 4, 6, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 2, 4, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 0, 2, 9, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 1, 7, 0, 6
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 2, 9, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_4, 0, 0, 12, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 0, 15, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 0, 6, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 4, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 1, 5, 0, 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 0, 12, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 2, 4, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 1, 5, 0, 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_7, 0, 3, 6, 5
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_8, 0, 1, 12, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_14, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_14, 0, 0, 12, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 1, 9, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 0, 12, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 4, 6, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127 
	voice_noise_alt 60, 0, 0, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 0, 1, 9, 1
	voice_noise_alt 60, 0, 0, 0, 1, 9, 0
	voice_noise_alt 60, 0, 0, 0, 1, 8, 1
	voice_noise_alt 60, 0, 0, 0, 2, 7, 0
	voice_noise_alt 60, 0, 0, 0, 2, 6, 0
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0
	voice_noise_alt 60, 0, 0, 0, 1, 6, 1
	voice_noise_alt 60, 0, 0, 0, 1, 6, 2
	voice_noise_alt 60, 0, 0, 0, 1, 6, 5
	voice_noise_alt 60, 0, 0, 0, 3, 5, 2
	voice_noise_alt 60, 0, 0, 0, 2, 4, 0
	voice_noise_alt 60, 0, 0, 0, 1, 3, 1
	voice_noise_alt 60, 0, 0, 0, 1, 3, 2
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0
	voice_noise_alt 60, 0, 0, 0, 1, 0, 1
