	.align 2
voicegroup335:: @ B2W2 Misc.
	voice_directsound 60, 0, DirectSoundWaveData_b2_unknown_screech, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_unknown_metalimpact, 255, 0, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_timpani_high, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_brasshit_high, 255, 0, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_brasshit_low, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_choirmale1_ghetsis, 255, 0, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_taikohardg4_ghetsis, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_choirmale3_ghetsis, 255, 0, 255, 1
	voice_keysplit voicegroup241, KeySplitTable25    @ tubular bell
	voice_keysplit voicegroup198, KeySplitTable9     @ fm ep (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_bw_074glocknc5, 255, 249, 0, 205
	voice_keysplit voicegroup244, KeySplitTable40    @ drawbar organ
	voice_keysplit voicegroup237, KeySplitTable83    @ rhodes 2 (hgss)
	voice_keysplit voicegroup323, KeySplitTable116   @ piano
	voice_directsound 60, 0, DirectSoundWaveData_bw_choirfemale1_ghetsis, 255, 0, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_choirfemale2_ghetsis, 255, 0, 227, 205
	voice_keysplit voicegroup291, KeySplitTable71    @ accordion
	voice_keysplit voicegroup345, KeySplitTable40    @ drawbar organ with attack
	voice_keysplit voicegroup206, KeySplitTable17    @ drawbar organ (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 219, 252, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_snaredark_ghetsis, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_synthbassd2, 255, 251, 0, 205
	voice_keysplit voicegroup255, KeySplitTable79    @ strings | 66
	voice_directsound 60, 0, DirectSoundWaveData_b2_suspensestringsc4, 255, 242, 191, 129
	voice_keysplit voicegroup203, KeySplitTable14    @ tubular bell (dppt)
	voice_keysplit voicegroup205, KeySplitTable16    @ rotary organ (dppt)
	voice_keysplit voicegroup207, KeySplitTable18    @ accordion (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 216
	voice_keysplit voicegroup261, KeySplitTable112   @ trumpets | 65
	voice_keysplit voicegroup255, KeySplitTable60    @ strings
	voice_keysplit voicegroup327, KeySplitTable72    @ french horns | 52 | 60
	voice_keysplit voicegroup256, KeySplitTable46    @ violin
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretlessbass_d1_16, 255, 0, 255, 192
	voice_keysplit voicegroup213, KeySplitTable24    @ violin (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_bw_064flt2a5, 255, 246, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_059harpc4, 255, 246, 0, 205
	voice_keysplit voicegroup312, KeySplitTable87    @ timpani (ghetsis)
	voice_directsound 60, 0, DirectSoundWaveData_hg_133timpg3, 255, 251, 0, 205
	voice_keysplit voicegroup261, KeySplitTable39    @ trumpets
	voice_keysplit_all voicegroup336				 @ drum set 1
	voice_keysplit voicegroup262, KeySplitTable27    @ trombones
	voice_programmable_wave 60, 0, ProgrammableWaveData_sq50half, 0, 3, 2, 2
	voice_square_2 60, 0, 2, 0, 3, 2, 2
	voice_square_1 60, 0, 0, 2, 0, 3, 2, 2
	voice_directsound 60, 0, DirectSoundWaveData_hg_021cellog2, 254, 242, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205
	voice_keysplit voicegroup216, KeySplitTable27    @ timpani 1 (dppt)
	voice_keysplit voicegroup217, KeySplitTable28    @ strings (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_b2_trombonesflutterb2, 255, 234, 210, 205
	voice_keysplit voicegroup223, KeySplitTable9     @ french horns (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_bw_trombonesstaccatocs2, 255, 1, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 1, 255, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220
	voice_keysplit voicegroup220, KeySplitTable30    @ trombone (dppt)
	voice_keysplit voicegroup289, KeySplitTable39    @ trumpets (short start)
	voice_keysplit voicegroup219, KeySplitTable29    @ trumpets 1 (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 28, 255, 127, 192
	voice_square_2 60, 0, 3, 1, 0, 15, 2
	voice_square_1 60, 0, 0, 3, 1, 0, 15, 2
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar1, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar2, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar3, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass_c1_16, 255, 1, 255, 216
	voice_directsound 60, 0, DirectSoundWaveData_bw_spiccatostringse2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_binaryleadc3, 255, 0, 255, 171
	voice_keysplit voicegroup303, KeySplitTable81    @ choir full
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196
	voice_programmable_wave 60, 0, ProgrammableWaveData_sq12halfoct, 0, 3, 11, 2
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlow_cs2_16, 255, 200, 255, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlowbra_b2_16, 255, 200, 255, 224
	voice_keysplit voicegroup218, KeySplitTable27    @ timpani 2 (dppt)
	voice_directsound 60, 0, DirectSoundWaveData_dp_octhit_c2_16, 255, 200, 255, 222
	voice_directsound 60, 0, DirectSoundWaveData_dp_sy_clarinet_c3_16, 255, 243, 159, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171
	voice_keysplit_all voicegroup337				 @ drum set 2
	voice_keysplit_all voicegroup338				 @ drum set 3 (addictive drums)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_gongf, 255, 251, 0, 205
	voice_keysplit voicegroup340, KeySplitTable118   @ pink strat
	voice_keysplit voicegroup340, KeySplitTable125   @ pink strat | 42 | 54
	voice_directsound 60, 0, DirectSoundWaveData_bw_guitarbendc5_plasma, 255, 197, 255, 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_tubad2, 255, 234, 210, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_stringsc3attack, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_stringsc3sustain, 255, 242, 191, 205
	voice_keysplit voicegroup299, KeySplitTable78    @ harp 2
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_timpanid2, 255, 0, 255, 205
	voice_keysplit voicegroup346, KeySplitTable122   @ cymbals
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_celloc2, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_stringsc3marcato, 255, 0, 255, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_synthbassd2, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_e_16, 255, 251, 0, 205
	voice_keysplit voicegroup261, KeySplitTable115   @ trumpets || 74
	voice_directsound 60, 0, DirectSoundWaveData_hg_141tbne3, 255, 242, 210, 205
	voice_keysplit voicegroup327, KeySplitTable68    @ french horns ||| 69
	voice_directsound 60, 0, DirectSoundWaveData_hg_096flt1c6, 255, 246, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_rhodesdmaj7, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_114marimc5, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_144tptc4, 255, 246, 210, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_123elastkc2, 255, 1, 227, 171
	voice_keysplit voicegroup294, KeySplitTable36    @ rhodes
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c3_16, 255, 0, 255, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_sawdmaj7, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_chiff, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_tani_falling, 255, 242, 191, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_145tptg5, 255, 246, 210, 205
