	.align 2
voicegroup291::
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_40_22, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_52_22, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_64_22, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_69_22, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_ew_goliath_pink_strat_81_22, 255, 254, 0, 178	@ 127/ 30/  1/120/ 64
