	.align 2
voicegroup356:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_eb_00, 255, 255, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_directsound 60, 0, DirectSoundWaveData_eb_03, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_directsound 60, 0, DirectSoundWaveData_eb_08, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_09, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_10, 255, 249, 0, 165
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_directsound 60, 0, DirectSoundWaveData_eb_20, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_21, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_22, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ dummy
	voice_directsound 60, 0, DirectSoundWaveData_eb_29, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_30, 255, 251, 0, 0
