	.align 2
voicegroup347:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_b2_squareleadd2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_squareleadd2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_squareleadd4, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_squareleadd4, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_squareleadd6, 255, 0, 255, 171
