	.align 2
voicegroup306::
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_36, 255, 64, 227, 178	@ 127/125/120/120/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_43, 255, 64, 227, 178	@ 127/125/120/120/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_48, 255, 64, 227, 178	@ 127/125/120/120/ 64
