	.align 2
voicegroup340::
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrate2, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrate3, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrate4, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrata4, 255, 253, 0, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrata5, 255, 253, 0, 171
