	.align 2
voicegroup331::
	voice_directsound 60, 0, DirectSoundWaveData_k64_synthvox0C_36, 255, 0, 255, 128
@	voice_directsound 60, 0, DirectSoundWaveData_k64_synthvox0C_57, 255, 0, 255, 128
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_k64_synthvox0C_69, 255, 0, 255, 128
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_k64_synthvox0C_81, 255, 0, 255, 128
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_k64_synthvox0C_93, 255, 0, 255, 128
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
