	.align 2
voicegroup256::
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_of_tutti_hit_minor_60, 255, 0, 225, 208	@ 127/127/127/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_of_tutti_hit_minor_63, 255, 0, 225, 208	@ 127/127/127/116/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_of_tutti_hit_minor_66, 255, 0, 225, 208	@ 127/127/127/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_of_tutti_hit_minor_69, 255, 0, 225, 208	@ 127/127/127/116/ 64
