	.align 2
voicegroup352:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_b2_gamelanc3, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_gamelanc4, 255, 251, 0, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_gamelanc4, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_gamelang4, 255, 251, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_gamelanc5, 255, 251, 0, 205
