	.align 2
voicegroup193::
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_017, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup204, KeySplitTable_pmd1_2
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_043, 29, 204, 154, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_054, 255, 249, 25, 226
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_054, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_055, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_056, 255, 0, 255, 216
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_057, 255, 0, 255, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup192
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_058, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_059, 255, 0, 255, 216
	voice_directsound 66, 64, DirectSoundWaveData_pmd1_wave_060, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_061, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_062, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_063, 255, 0, 255, 216
	voice_noise_alt 80, 64, 0, 0, 1, 0, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_064, 255, 0, 255, 127
	voice_noise_alt 78, 64, 0, 0, 1, 0, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_065, 255, 0, 255, 165
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 100, 64, 0, 0, 2, 0, 0
	voice_noise_alt 100, 64, 0, 0, 2, 6, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_066, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_067, 255, 0, 255, 204
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_068, 255, 0, 255, 204
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_069, 255, 0, 255, 204
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_070, 255, 0, 255, 204
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_071, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_055, 255, 0, 255, 216
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_072, 255, 0, 255, 216
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_073, 255, 0, 255, 216
	voice_noise_alt 80, 64, 0, 0, 1, 0, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_074, 255, 0, 255, 216
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_075, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_076, 255, 249, 0, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_077, 255, 226, 0, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_058, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_059, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_078, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_064, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_079, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_080, 255, 0, 255, 216
	voice_noise_alt 80, 64, 0, 0, 1, 0, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_081, 255, 0, 255, 216
	voice_noise_alt 78, 64, 0, 0, 1, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_061, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 34, DirectSoundWaveData_pmd1_wave_082, 64, 226, 0, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_082, 255, 226, 0, 0
	voice_directsound 60, 94, DirectSoundWaveData_pmd1_wave_082, 64, 226, 0, 0
	voice_noise_alt 100, 64, 0, 0, 2, 0, 0
	voice_noise_alt 100, 64, 0, 0, 2, 6, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_066, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_083, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_071, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_067, 255, 0, 255, 204
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_068, 255, 0, 255, 204
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_069, 255, 0, 255, 204
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_070, 255, 0, 255, 204
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_056, 255, 0, 255, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_057, 255, 0, 255, 127
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_084, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 80, 64, 0, 0, 1, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_055, 255, 0, 255, 216
	voice_directsound 60, 44, DirectSoundWaveData_pmd1_wave_072, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 84, DirectSoundWaveData_pmd1_wave_073, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_074, 255, 0, 255, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_076, 255, 249, 0, 216
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_wave_077, 255, 226, 0, 216
