	.align 2
voicegroup307::
	voice_directsound 60, 0, DirectSoundWaveData_b2_plugsound_pro_classical_piano1_29, 255, 251, 0, 48	@ 127/ 60/  1/125/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_plugsound_pro_classical_piano1_41, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_plugsound_pro_classical_piano1_53, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_plugsound_pro_classical_piano1_65, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_b2_plugsound_pro_classical_piano1_77, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
