	.align 2
voicegroup333:: @ B2W2 Ichinose
	voice_keysplit voicegroup323, KeySplitTable116   @ piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_bw_063rhodc5, 255, 250, 0, 210
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup234, KeySplitTable36    @ piano 2
	voice_keysplit voicegroup341, KeySplitTable120   @ piano 3
	voice_keysplit voicegroup332, KeySplitTable114   @ piano (longer decay)
	voice_keysplit voicegroup323, KeySplitTable93    @ piano | 41 | 46 | 53 | 58 | 65
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup240, KeySplitTable115   @ xylophone || 74
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup241, KeySplitTable25    @ tubular bell
	voice_directsound 60, 0, DirectSoundWaveData_bw_074glocknc5, 255, 249, 0, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup244, KeySplitTable71    @ drawbar organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup292, KeySplitTable72    @ nylon str. guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_b2_pinkstrate3, 255, 253, 0, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup316, KeySplitTable41    @ clean guitar
	voice_directsound 60, 0, DirectSoundWaveData_hg_001uprigc3, 255, 251, 0, 192
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup311, KeySplitTable101   @ fretless bass | 34
	voice_keysplit voicegroup309, KeySplitTable117   @ slap bass | 47 |
	voice_keysplit voicegroup254, KeySplitTable73    @ synth bass
	voice_keysplit voicegroup255, KeySplitTable60    @ strings
	voice_keysplit voicegroup255, KeySplitTable79    @ strings | 66
	voice_keysplit voicegroup256, KeySplitTable46    @ violin
	voice_directsound 60, 0, DirectSoundWaveData_hg_021cellog2, 254, 242, 255, 205
	voice_keysplit voicegroup293, KeySplitTable48    @ pizzicato
	voice_keysplit voicegroup299, KeySplitTable78    @ harp 2
	voice_keysplit voicegroup302, KeySplitTable80    @ harp 1
	voice_keysplit voicegroup261, KeySplitTable112   @ trumpets | 65
	voice_directsound 60, 0, DirectSoundWaveData_hg_133timpg3, 255, 251, 0, 205
	voice_keysplit voicegroup261, KeySplitTable39    @ trumpets
	voice_keysplit voicegroup262, KeySplitTable27    @ trombones
	voice_keysplit voicegroup327, KeySplitTable72    @ french horns | 52 | 60
	voice_keysplit voicegroup327, KeySplitTable41    @ french horns
	voice_keysplit voicegroup305, KeySplitTable44    @ tuba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup266, KeySplitTable52    @ clarinet
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_bw_064flt2a5, 255, 246, 159, 205
	voice_keysplit voicegroup328, KeySplitTable65    @ flute 1
	voice_directsound 60, 0, DirectSoundWaveData_hg_096flt1c6, 255, 246, 159, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchhitas2_leader, 255, 248, 0, 205
	voice_keysplit voicegroup289, KeySplitTable39    @ trumpets (short start)
	voice_directsound 60, 0, DirectSoundWaveData_hg_059harpc4, 255, 246, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_098pizza4, 255, 248, 0, 205
	voice_keysplit voicegroup312, KeySplitTable87    @ timpani (ghetsis)
	voice_keysplit voicegroup327, KeySplitTable68    @ french horns ||| 69
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 0, 255, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_bw_sawleadc4_vsleader, 255, 242, 191, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_bw_synthbassf1_leader, 255, 251, 14, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_b2_metalclanke2, 255, 250, 0, 220
	voice_directsound 60, 0, DirectSoundWaveData_b2_hardbasse2, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_hardbasse3, 255, 0, 252, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_recorderg5, 255, 1, 227, 129
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar1, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar2, 255, 197, 159, 192
	voice_directsound 60, 0, DirectSoundWaveData_b2_powerguitar3, 255, 197, 159, 192
	voice_keysplit_all voicegroup336				 @ drum set 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit_all voicegroup338				 @ drum set 3 (addictive drums)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_bw_solotrumpetc5, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_trombonesstaccatocs2, 255, 1, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_spiccatostringse2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_b2_trumpetsstaccatogs4_loop, 255, 0, 255, 224
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit voicegroup340, KeySplitTable118   @ pink strat
	voice_keysplit voicegroup340, KeySplitTable119   @ pink strat | 42 | 54 | 68
	voice_keysplit voicegroup340, KeySplitTable125   @ pink strat | 42 | 54
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_bw_reversecymbale2, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_reversecymbale2, 255, 0, 255, 236
	voice_directsound 60, 0, DirectSoundWaveData_b2_electricityspark, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_2 60, 0, 1, 0, 3, 10, 3
	voice_programmable_wave 60, 0, ProgrammableWaveData_sq50half, 0, 3, 10, 3 
	voice_square_2 60, 0, 2, 0, 3, 10, 3
	voice_square_1 60, 0, 0, 2, 0, 3, 10, 3
	voice_square_1 60, 0, 0, 1, 0, 3, 10, 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_keysplit_all voicegroup343				 @ various vocal chops and other samples
	voice_directsound 60, 0, DirectSoundWaveData_b2_nimbasagymsynthe1, 255, 242, 227, 214
	voice_directsound 60, 0, DirectSoundWaveData_b2_nimbasagymsynthe4, 255, 242, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_nimbasagymsynthe6, 255, 242, 227, 205
	voice_directsound 60, 0, DirectSoundWaveData_b2_drumloop_nimbasagym, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                          @ placeholder
	voice_directsound 60, 0, DirectSoundWaveData_b2_virbankgym_female1_sing, 255, 0, 252, 1
