	.align 2
voicegroup316::
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_electric_sitar_48, 255, 252, 0, 208	@ 127/ 55/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_electric_sitar_57, 255, 252, 0, 197	@ 127/ 55/  1/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_electric_sitar_65, 255, 252, 0, 208	@ 127/ 55/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_electric_sitar_74, 255, 252, 0, 208	@ 127/ 55/  1/116/ 64
