	.align 2
voicegroup304::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 48, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 49, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 50, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 51, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 52, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 53, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 54, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 55, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 56, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 57, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, 2, 0, 227, 178				@   3/127/120/120/ 64
	voice_directsound 60, 64, DirectSoundWaveData_b2_halion_t9_analog_kick_22, 255, 0, 227, 48				@ 127/127/120/125/ 64
	voice_directsound 61, 64, DirectSoundWaveData_b2_halion_t9_analog_kick_22, 255, 0, 227, 48				@ 127/127/120/125/ 64
	voice_directsound 62, 64, DirectSoundWaveData_b2_halion_t9_analog_kick_22, 255, 0, 227, 48				@ 127/127/120/125/ 64
	voice_directsound 63, 64, DirectSoundWaveData_b2_halion_t9_analog_kick_22, 255, 0, 227, 48				@ 127/127/120/125/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 64, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 65, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 66, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 67, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 68, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 69, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 70, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 71, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 72, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 73, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 74, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 75, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 76, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 77, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 78, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 79, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare, 255, 0, 227, 48		@ 127/127/120/125/ 64
	voice_directsound 60, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 62, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 63, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 64, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 65, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 66, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 67, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 68, 80, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 80
	voice_directsound 60, 30, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 30
	voice_directsound 61, 30, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 30
	voice_directsound 62, 30, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 30
	voice_directsound 63, 30, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 246, 0, 216	@ 127/ 90/  0/114/ 30
	voice_directsound 60, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 64, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 65, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 66, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 67, 64, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 247, 0, 216	@ 127/ 88/  0/114/ 64
	voice_directsound 60, 114, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/114
	voice_directsound 60, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 61, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 62, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 63, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 64, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 65, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 66, 14, DirectSoundWaveData_bw_battery3_rock_cymbal2, 255, 249, 0, 216	@ 127/ 80/  0/114/ 14
	voice_directsound 60, 64, DirectSoundWaveData_b2_ew_ra_chinese_gong_vs_2, 255, 0, 255, 0	@ 127/127/127/127/ 64
