	.align 2
voicegroup355::
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_timpani_55, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_timpani_60, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_timpani_67, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
