	.align 2
voicegroup325::
	voice_directsound 24, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 25, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 26, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 27, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 28, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 29, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 30, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 31, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 32, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 33, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 34, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 35, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 36, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 37, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 38, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 39, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 40, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 41, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 42, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 43, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 44, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 45, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 50, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 51, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 52, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 53, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 54, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 55, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 56, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 57, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 58, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 59, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_directsound 60, 20, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 100, DirectSoundWaveData_k64_chh, 255, 0, 255, 88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 53, 51, DirectSoundWaveData_k64_ride, 255, 0, 255, 88
	voice_directsound 54, 51, DirectSoundWaveData_k64_ride, 255, 0, 255, 88
	voice_directsound 55, 51, DirectSoundWaveData_k64_ride, 255, 0, 255, 88
	voice_directsound 54, 33, DirectSoundWaveData_k64_tambourine, 255, 0, 255, 88
	voice_directsound 92, 30, DirectSoundWaveData_k64_crash, 255, 0, 255, 88
	voice_directsound 93, 30, DirectSoundWaveData_k64_crash, 255, 0, 255, 88
	voice_directsound 83, 49, DirectSoundWaveData_k64_crash, 255, 0, 255, 88
	voice_directsound 84, 49, DirectSoundWaveData_k64_crash, 255, 0, 255, 88
	voice_directsound 85, 49, DirectSoundWaveData_k64_crash, 255, 0, 255, 88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 61, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 62, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 63, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 64, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 65, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 66, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 67, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_directsound 68, 64, DirectSoundWaveData_k64_sfx_kick, 255, 0, 255, 88
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_drumloop2a, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_drumloop2b, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_drumloop2c, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_drumloop1a, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_drumloop1b, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 61, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 62, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 63, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 64, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 65, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 66, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 67, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 68, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 69, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 70, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 71, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 72, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 73, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 74, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 75, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 76, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 77, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 78, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
	voice_directsound 79, 64, DirectSoundWaveData_k64_drumloop1c, 255, 0, 255, 0
