	.align 2
voicegroup207::
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_012, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_009, 255, 0, 255, 0
	voice_keysplit voicegroup208, KeySplitTable_pmd1_6
	voice_keysplit voicegroup209, KeySplitTable_pmd1_5
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_027, 255, 188, 206, 188
	voice_keysplit voicegroup210, KeySplitTable_pmd1_4
	voice_keysplit voicegroup211, KeySplitTable_pmd1_3
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_005, 255, 165, 154, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_014, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_014, 255, 165, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_028, 255, 226, 0, 127
	voice_keysplit voicegroup212, KeySplitTable_pmd1_5
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_027, 255, 188, 180, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_029, 255, 188, 180, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_006, 255, 249, 25, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_030, 13, 0, 255, 127
	voice_keysplit voicegroup213, KeySplitTable_pmd1_8
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_004, 255, 0, 255, 149
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_015, 255, 0, 255, 127
	voice_keysplit voicegroup214, KeySplitTable_pmd1_1
	voice_keysplit voicegroup215, KeySplitTable_pmd1_1
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_031, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_032, 37, 0, 255, 0
	voice_keysplit voicegroup216, KeySplitTable_pmd1_0
	voice_keysplit voicegroup217, KeySplitTable_pmd1_7
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_033, 255, 188, 103, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_034, 64, 249, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_001, 64, 204, 103, 188
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_013, 64, 235, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_035, 255, 235, 255, 188
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_033, 64, 0, 103, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_012, 64, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_036, 255, 204, 51, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_037, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_006, 255, 204, 51, 0
	voice_keysplit voicegroup213, KeySplitTable_pmd1_9
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_038, 64, 255, 0, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_039, 37, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_040, 37, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_041, 37, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_042, 37, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_085, 64, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_086, 64, 249, 25, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_013, 128, 235, 255, 242
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_087, 64, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_088, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_002, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_002, 255, 216, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_000, 255, 188, 77, 242
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_051, 255, 216, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_052, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_053, 255, 188, 154, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_043, 15, 0, 255, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_044, 19, 165, 206, 216
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_044, 26, 165, 206, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_043, 26, 0, 255, 204
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_044, 37, 165, 206, 204
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 1, 0, 1
	voice_square_2_alt 60, 0, 2, 0, 2, 1, 0
	voice_square_2_alt 60, 0, 1, 0, 1, 0, 1
	voice_square_2_alt 60, 0, 1, 0, 2, 1, 0
	voice_square_2_alt 60, 0, 0, 0, 1, 0, 1
	voice_square_2_alt 60, 0, 0, 0, 2, 1, 0
	voice_square_2_alt 60, 0, 2, 0, 3, 3, 0
	voice_square_1_alt 60, 0, 0, 2, 1, 3, 12, 1
	voice_square_1_alt 60, 0, 0, 2, 1, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 0, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 1, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 0, 1
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 1, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 0, 1
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 1, 0
	voice_square_2_alt 60, 0, 2, 1, 1, 0, 0
	voice_square_2_alt 60, 0, 1, 1, 1, 0, 0
	voice_square_2_alt 60, 0, 0, 1, 1, 0, 0
	voice_square_1_alt 60, 0, 0, 2, 1, 1, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 1, 1, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 1, 1, 0, 0
	voice_square_2_alt 60, 0, 2, 1, 3, 12, 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_001, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_015, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_000, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_003, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_017, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd1_010, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 1, 0, 7, 0
	voice_noise_alt 60, 0, 0, 0, 4, 3, 2
	voice_noise_alt 60, 0, 0, 0, 5, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_082, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_056, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_083, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_082, 10, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_055, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_066, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_054, 255, 242, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_054, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_082, 255, 0, 255, 242
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_064, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_084, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_wave_082, 255, 255, 0, 204
	voice_keysplit_all voicegroup193
