	.align 2
voicegroup281::
	voice_directsound 60, 0, DirectSoundWaveData_bw_kfl_trombone_ensemble_43, 255, 242, 210, 208	@ 127/100/115/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_kfl_trombone_ensemble_52, 255, 242, 210, 208	@ 127/100/115/116/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_bw_kfl_trombone_ensemble_60, 255, 242, 210, 208	@ 127/100/115/116/ 64	@ todo: get adsr
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
