#ifndef GUARD_CONFIG_MUSIC_EXPANSION_V3_H
#define GUARD_CONFIG_MUSIC_EXPANSION_V3_H

// Song definitions. By default, I have disabled the songs that go unused in vanilla Pokémon Emerald

// Ruby / Sapphire sound effects
#define MUX_SE_USE_ITEM               TRUE
#define MUX_SE_PC_LOGIN               TRUE
#define MUX_SE_PC_OFF                 TRUE
#define MUX_SE_PC_ON                  TRUE
#define MUX_SE_SELECT                 TRUE
#define MUX_SE_WIN_OPEN               TRUE
#define MUX_SE_WALL_HIT               TRUE
#define MUX_SE_DOOR                   TRUE
#define MUX_SE_EXIT                   TRUE
#define MUX_SE_LEDGE                  TRUE
#define MUX_SE_BIKE_BELL              FALSE
#define MUX_SE_NOT_EFFECTIVE          TRUE
#define MUX_SE_EFFECTIVE              TRUE
#define MUX_SE_SUPER_EFFECTIVE        TRUE
#define MUX_SE_BALL_OPEN              TRUE
#define MUX_SE_FAINT                  TRUE
#define MUX_SE_FLEE                   TRUE
#define MUX_SE_SLIDING_DOOR           TRUE
#define MUX_SE_SHIP                   FALSE
#define MUX_SE_BANG                   TRUE
#define MUX_SE_PIN                    TRUE
#define MUX_SE_BOO                    TRUE
#define MUX_SE_BALL                   TRUE
#define MUX_SE_CONTEST_PLACE          TRUE
#define MUX_SE_A                      FALSE
#define MUX_SE_I                      FALSE
#define MUX_SE_U                      FALSE
#define MUX_SE_E                      FALSE
#define MUX_SE_O                      FALSE
#define MUX_SE_N                      FALSE
#define MUX_SE_SUCCESS                TRUE
#define MUX_SE_FAILURE                TRUE
#define MUX_SE_EXP                    TRUE
#define MUX_SE_BIKE_HOP               TRUE
#define MUX_SE_SWITCH                 TRUE
#define MUX_SE_CLICK                  TRUE
#define MUX_SE_FU_ZAKU                FALSE
#define MUX_SE_CONTEST_CONDITION_LOSE TRUE
#define MUX_SE_LAVARIDGE_FALL_WARP    TRUE
#define MUX_SE_ICE_STAIRS             TRUE
#define MUX_SE_ICE_BREAK              TRUE
#define MUX_SE_ICE_CRACK              TRUE
#define MUX_SE_FALL                   TRUE
#define MUX_SE_UNLOCK                 TRUE
#define MUX_SE_WARP_IN                TRUE
#define MUX_SE_WARP_OUT               TRUE
#define MUX_SE_REPEL                  TRUE
#define MUX_SE_ROTATING_GATE          TRUE
#define MUX_SE_TRUCK_MOVE             TRUE
#define MUX_SE_TRUCK_STOP             TRUE
#define MUX_SE_TRUCK_UNLOAD           TRUE
#define MUX_SE_TRUCK_DOOR             TRUE
#define MUX_SE_BERRY_BLENDER          TRUE
#define MUX_SE_CARD                   FALSE
#define MUX_SE_SAVE                   TRUE
#define MUX_SE_BALL_BOUNCE_1          TRUE
#define MUX_SE_BALL_BOUNCE_2          TRUE
#define MUX_SE_BALL_BOUNCE_3          TRUE
#define MUX_SE_BALL_BOUNCE_4          TRUE
#define MUX_SE_BALL_TRADE             TRUE
#define MUX_SE_BALL_THROW             TRUE
#define MUX_SE_NOTE_C                 TRUE
#define MUX_SE_NOTE_D                 TRUE
#define MUX_SE_NOTE_E                 TRUE
#define MUX_SE_NOTE_F                 TRUE
#define MUX_SE_NOTE_G                 TRUE
#define MUX_SE_NOTE_A                 TRUE
#define MUX_SE_NOTE_B                 TRUE
#define MUX_SE_NOTE_C_HIGH            TRUE
#define MUX_SE_PUDDLE                 TRUE
#define MUX_SE_BRIDGE_WALK            TRUE
#define MUX_SE_ITEMFINDER             TRUE
#define MUX_SE_DING_DONG              TRUE
#define MUX_SE_BALLOON_RED            TRUE
#define MUX_SE_BALLOON_BLUE           TRUE
#define MUX_SE_BALLOON_YELLOW         TRUE
#define MUX_SE_BREAKABLE_DOOR         TRUE
#define MUX_SE_MUD_BALL               TRUE
#define MUX_SE_FIELD_POISON           TRUE
#define MUX_SE_ESCALATOR              TRUE
#define MUX_SE_THUNDERSTORM           TRUE
#define MUX_SE_THUNDERSTORM_STOP      TRUE
#define MUX_SE_DOWNPOUR               TRUE
#define MUX_SE_DOWNPOUR_STOP          TRUE
#define MUX_SE_RAIN                   TRUE
#define MUX_SE_RAIN_STOP              TRUE
#define MUX_SE_THUNDER                TRUE
#define MUX_SE_THUNDER2               TRUE
#define MUX_SE_ELEVATOR               TRUE
#define MUX_SE_LOW_HEALTH             TRUE
#define MUX_SE_EXP_MAX                TRUE
#define MUX_SE_ROULETTE_BALL          TRUE
#define MUX_SE_ROULETTE_BALL2         TRUE
#define MUX_SE_TAILLOW_WING_FLAP      TRUE
#define MUX_SE_SHOP                   TRUE
#define MUX_SE_CONTEST_HEART          TRUE
#define MUX_SE_CONTEST_CURTAIN_RISE   TRUE
#define MUX_SE_CONTEST_CURTAIN_FALL   TRUE
#define MUX_SE_CONTEST_ICON_CHANGE    TRUE
#define MUX_SE_CONTEST_ICON_CLEAR     TRUE
#define MUX_SE_CONTEST_MONS_TURN      TRUE
#define MUX_SE_SHINY                  TRUE
#define MUX_SE_INTRO_BLAST            TRUE
#define MUX_SE_MUGSHOT                TRUE
#define MUX_SE_APPLAUSE               TRUE
#define MUX_SE_VEND                   TRUE
#define MUX_SE_ORB                    TRUE
#define MUX_SE_DEX_SCROLL             TRUE
#define MUX_SE_DEX_PAGE               TRUE
#define MUX_SE_POKENAV_ON             TRUE
#define MUX_SE_POKENAV_OFF            TRUE
#define MUX_SE_DEX_SEARCH             TRUE
#define MUX_SE_EGG_HATCH              TRUE
#define MUX_SE_BALL_TRAY_ENTER        TRUE
#define MUX_SE_BALL_TRAY_BALL         TRUE
#define MUX_SE_BALL_TRAY_EXIT         TRUE
#define MUX_SE_GLASS_FLUTE            TRUE
// Move SFX
#define MUX_SE_M_THUNDERBOLT          TRUE
#define MUX_SE_M_THUNDERBOLT2         TRUE
#define MUX_SE_M_HARDEN               TRUE
#define MUX_SE_M_NIGHTMARE            TRUE
#define MUX_SE_M_VITAL_THROW          TRUE
#define MUX_SE_M_VITAL_THROW2         TRUE
#define MUX_SE_M_BUBBLE               TRUE
#define MUX_SE_M_BUBBLE2              TRUE
#define MUX_SE_M_BUBBLE3              TRUE
#define MUX_SE_M_RAIN_DANCE           TRUE
#define MUX_SE_M_CUT                  TRUE
#define MUX_SE_M_STRING_SHOT          TRUE
#define MUX_SE_M_STRING_SHOT2         TRUE
#define MUX_SE_M_ROCK_THROW           TRUE
#define MUX_SE_M_GUST                 TRUE
#define MUX_SE_M_GUST2                TRUE
#define MUX_SE_M_DOUBLE_SLAP          TRUE
#define MUX_SE_M_DOUBLE_TEAM          TRUE
#define MUX_SE_M_RAZOR_WIND           TRUE
#define MUX_SE_M_ICY_WIND             TRUE
#define MUX_SE_M_THUNDER_WAVE         TRUE
#define MUX_SE_M_COMET_PUNCH          TRUE
#define MUX_SE_M_MEGA_KICK            TRUE
#define MUX_SE_M_MEGA_KICK2           TRUE
#define MUX_SE_M_CRABHAMMER           TRUE
#define MUX_SE_M_JUMP_KICK            TRUE
#define MUX_SE_M_FLAME_WHEEL          TRUE
#define MUX_SE_M_FLAME_WHEEL2         TRUE
#define MUX_SE_M_FLAMETHROWER         TRUE
#define MUX_SE_M_FIRE_PUNCH           TRUE
#define MUX_SE_M_TOXIC                TRUE
#define MUX_SE_M_SACRED_FIRE          TRUE
#define MUX_SE_M_SACRED_FIRE2         TRUE
#define MUX_SE_M_EMBER                TRUE
#define MUX_SE_M_TAKE_DOWN            TRUE
#define MUX_SE_M_BLIZZARD             TRUE
#define MUX_SE_M_BLIZZARD2            TRUE
#define MUX_SE_M_SCRATCH              TRUE
#define MUX_SE_M_VICEGRIP             TRUE
#define MUX_SE_M_WING_ATTACK          TRUE
#define MUX_SE_M_FLY                  TRUE
#define MUX_SE_M_SAND_ATTACK          TRUE
#define MUX_SE_M_RAZOR_WIND2          TRUE
#define MUX_SE_M_BITE                 TRUE
#define MUX_SE_M_HEADBUTT             TRUE
#define MUX_SE_M_SURF                 TRUE
#define MUX_SE_M_HYDRO_PUMP           TRUE
#define MUX_SE_M_WHIRLPOOL            TRUE
#define MUX_SE_M_HORN_ATTACK          TRUE
#define MUX_SE_M_TAIL_WHIP            TRUE
#define MUX_SE_M_MIST                 TRUE
#define MUX_SE_M_POISON_POWDER        TRUE
#define MUX_SE_M_BIND                 TRUE
#define MUX_SE_M_DRAGON_RAGE          TRUE
#define MUX_SE_M_SING                 TRUE
#define MUX_SE_M_PERISH_SONG          TRUE
#define MUX_SE_M_PAY_DAY              TRUE
#define MUX_SE_M_DIG                  TRUE
#define MUX_SE_M_DIZZY_PUNCH          TRUE
#define MUX_SE_M_SELF_DESTRUCT        TRUE
#define MUX_SE_M_EXPLOSION            TRUE
#define MUX_SE_M_ABSORB_2             TRUE
#define MUX_SE_M_ABSORB               TRUE
#define MUX_SE_M_SCREECH              TRUE
#define MUX_SE_M_BUBBLE_BEAM          TRUE
#define MUX_SE_M_BUBBLE_BEAM2         TRUE
#define MUX_SE_M_SUPERSONIC           TRUE
#define MUX_SE_M_BELLY_DRUM           TRUE
#define MUX_SE_M_METRONOME            TRUE
#define MUX_SE_M_BONEMERANG           TRUE
#define MUX_SE_M_LICK                 TRUE
#define MUX_SE_M_PSYBEAM              TRUE
#define MUX_SE_M_FAINT_ATTACK         TRUE
#define MUX_SE_M_SWORDS_DANCE         TRUE
#define MUX_SE_M_LEER                 TRUE
#define MUX_SE_M_SWAGGER              TRUE
#define MUX_SE_M_SWAGGER2             TRUE
#define MUX_SE_M_HEAL_BELL            TRUE
#define MUX_SE_M_CONFUSE_RAY          TRUE
#define MUX_SE_M_SNORE                TRUE
#define MUX_SE_M_BRICK_BREAK          TRUE
#define MUX_SE_M_GIGA_DRAIN           TRUE
#define MUX_SE_M_PSYBEAM2             TRUE
#define MUX_SE_M_SOLAR_BEAM           TRUE
#define MUX_SE_M_PETAL_DANCE          TRUE
#define MUX_SE_M_TELEPORT             TRUE
#define MUX_SE_M_MINIMIZE             TRUE
#define MUX_SE_M_SKETCH               TRUE
#define MUX_SE_M_SWIFT                TRUE
#define MUX_SE_M_REFLECT              TRUE
#define MUX_SE_M_BARRIER              TRUE
#define MUX_SE_M_DETECT               TRUE
#define MUX_SE_M_LOCK_ON              TRUE
#define MUX_SE_M_MOONLIGHT            TRUE
#define MUX_SE_M_CHARM                TRUE
#define MUX_SE_M_CHARGE               TRUE
#define MUX_SE_M_STRENGTH             TRUE
#define MUX_SE_M_HYPER_BEAM           TRUE
#define MUX_SE_M_WATERFALL            TRUE
#define MUX_SE_M_REVERSAL             TRUE
#define MUX_SE_M_ACID_ARMOR           TRUE
#define MUX_SE_M_SANDSTORM            TRUE
#define MUX_SE_M_TRI_ATTACK           TRUE
#define MUX_SE_M_TRI_ATTACK2          TRUE
#define MUX_SE_M_ENCORE               TRUE
#define MUX_SE_M_ENCORE2              TRUE
#define MUX_SE_M_BATON_PASS           TRUE
#define MUX_SE_M_MILK_DRINK           TRUE
#define MUX_SE_M_ATTRACT              TRUE
#define MUX_SE_M_ATTRACT2             TRUE
#define MUX_SE_M_MORNING_SUN          TRUE
#define MUX_SE_M_FLATTER              TRUE
#define MUX_SE_M_SAND_TOMB            TRUE
#define MUX_SE_M_GRASSWHISTLE         TRUE
#define MUX_SE_M_SPIT_UP              TRUE
#define MUX_SE_M_DIVE                 TRUE
#define MUX_SE_M_EARTHQUAKE           TRUE
#define MUX_SE_M_TWISTER              TRUE
#define MUX_SE_M_SWEET_SCENT          TRUE
#define MUX_SE_M_YAWN                 TRUE
#define MUX_SE_M_SKY_UPPERCUT         TRUE
#define MUX_SE_M_STAT_INCREASE        TRUE
#define MUX_SE_M_HEAT_WAVE            TRUE
#define MUX_SE_M_UPROAR               TRUE
#define MUX_SE_M_HAIL                 TRUE
#define MUX_SE_M_COSMIC_POWER         TRUE
#define MUX_SE_M_TEETER_DANCE         TRUE
#define MUX_SE_M_STAT_DECREASE        TRUE
#define MUX_SE_M_HAZE                 TRUE
#define MUX_SE_M_HYPER_BEAM2          TRUE
// FireRed / LeafGreen sound effects
#define MUX_SE_RG_DOOR                FALSE
#define MUX_SE_RG_CARD_FLIP           TRUE
#define MUX_SE_RG_CARD_FLIPPING       TRUE
#define MUX_SE_RG_CARD_OPEN           TRUE
#define MUX_SE_RG_BAG_CURSOR          FALSE
#define MUX_SE_RG_BAG_POCKET          TRUE
#define MUX_SE_RG_BALL_CLICK          TRUE
#define MUX_SE_RG_SHOP                FALSE
#define MUX_SE_RG_SS_ANNE_HORN        FALSE
#define MUX_SE_RG_HELP_OPEN           FALSE
#define MUX_SE_RG_HELP_CLOSE          FALSE
#define MUX_SE_RG_HELP_ERROR          FALSE
#define MUX_SE_RG_DEOXYS_MOVE         TRUE
#define MUX_SE_RG_POKE_JUMP_SUCCESS   TRUE
#define MUX_SE_RG_POKE_JUMP_FAILURE   TRUE
// Emerald sound effects
#define MUX_SE_POKENAV_CALL           TRUE
#define MUX_SE_POKENAV_HANG_UP        TRUE
#define MUX_SE_ARENA_TIMEUP1          TRUE
#define MUX_SE_ARENA_TIMEUP2          TRUE
#define MUX_SE_PIKE_CURTAIN_CLOSE     TRUE
#define MUX_SE_PIKE_CURTAIN_OPEN      TRUE
#define MUX_SE_SUDOWOODO_SHAKE        TRUE

#define MUX_ENABLE_BARD_PHONEMES      TRUE

// Ruby / Sapphire / Emerald music
#define MUX_MUS_LITTLEROOT_TEST         FALSE
#define MUX_MUS_GSC_ROUTE38             FALSE
#define MUX_MUS_CAUGHT                  TRUE
#define MUX_MUS_VICTORY_WILD            TRUE
#define MUX_MUS_VICTORY_GYM_LEADER      TRUE
#define MUX_MUS_VICTORY_LEAGUE          TRUE
#define MUX_MUS_C_COMM_CENTER           FALSE
#define MUX_MUS_GSC_PEWTER              TRUE
#define MUX_MUS_C_VS_LEGEND_BEAST       FALSE
#define MUX_MUS_ROUTE101                TRUE
#define MUX_MUS_ROUTE110                TRUE
#define MUX_MUS_ROUTE120                TRUE
#define MUX_MUS_PETALBURG               TRUE
#define MUX_MUS_OLDALE                  TRUE
#define MUX_MUS_GYM                     TRUE
#define MUX_MUS_SURF                    TRUE
#define MUX_MUS_PETALBURG_WOODS         TRUE
#define MUX_MUS_LEVEL_UP                TRUE
#define MUX_MUS_HEAL                    TRUE
#define MUX_MUS_OBTAIN_BADGE            TRUE
#define MUX_MUS_OBTAIN_ITEM             TRUE
#define MUX_MUS_EVOLVED                 TRUE
#define MUX_MUS_OBTAIN_TMHM             TRUE
#define MUX_MUS_LILYCOVE_MUSEUM         TRUE
#define MUX_MUS_ROUTE122                TRUE
#define MUX_MUS_OCEANIC_MUSEUM          TRUE
#define MUX_MUS_EVOLUTION_INTRO         TRUE
#define MUX_MUS_EVOLUTION               TRUE
#define MUX_MUS_MOVE_DELETED            TRUE
#define MUX_MUS_ENCOUNTER_GIRL          TRUE
#define MUX_MUS_ENCOUNTER_MALE          TRUE
#define MUX_MUS_ABANDONED_SHIP          TRUE
#define MUX_MUS_FORTREE                 TRUE
#define MUX_MUS_BIRCH_LAB               TRUE
#define MUX_MUS_B_TOWER_RS              TRUE
#define MUX_MUS_ENCOUNTER_SWIMMER       TRUE
#define MUX_MUS_CAVE_OF_ORIGIN          TRUE
#define MUX_MUS_OBTAIN_BERRY            TRUE
#define MUX_MUS_AWAKEN_LEGEND           TRUE
#define MUX_MUS_SLOTS_JACKPOT           TRUE
#define MUX_MUS_SLOTS_WIN               TRUE
#define MUX_MUS_TOO_BAD                 TRUE
#define MUX_MUS_ROULETTE                TRUE
#define MUX_MUS_LINK_CONTEST_P1         TRUE
#define MUX_MUS_LINK_CONTEST_P2         TRUE
#define MUX_MUS_LINK_CONTEST_P3         TRUE
#define MUX_MUS_LINK_CONTEST_P4         TRUE
#define MUX_MUS_ENCOUNTER_RICH          TRUE
#define MUX_MUS_VERDANTURF              TRUE
#define MUX_MUS_RUSTBORO                TRUE
#define MUX_MUS_POKE_CENTER             TRUE
#define MUX_MUS_ROUTE104                TRUE
#define MUX_MUS_ROUTE119                TRUE
#define MUX_MUS_CYCLING                 TRUE
#define MUX_MUS_POKE_MART               TRUE
#define MUX_MUS_LITTLEROOT              TRUE
#define MUX_MUS_MT_CHIMNEY              TRUE
#define MUX_MUS_ENCOUNTER_FEMALE        TRUE
#define MUX_MUS_LILYCOVE                TRUE
#define MUX_MUS_DESERT                  TRUE
#define MUX_MUS_HELP                    TRUE
#define MUX_MUS_UNDERWATER              TRUE
#define MUX_MUS_VICTORY_TRAINER         TRUE
#define MUX_MUS_TITLE                   TRUE
#define MUX_MUS_INTRO                   TRUE
#define MUX_MUS_ENCOUNTER_MAY           TRUE
#define MUX_MUS_ENCOUNTER_INTENSE       TRUE
#define MUX_MUS_ENCOUNTER_COOL          TRUE
#define MUX_MUS_ROUTE113                TRUE
#define MUX_MUS_ENCOUNTER_AQUA          TRUE
#define MUX_MUS_FOLLOW_ME               TRUE
#define MUX_MUS_ENCOUNTER_BRENDAN       TRUE
#define MUX_MUS_EVER_GRANDE             TRUE
#define MUX_MUS_ENCOUNTER_SUSPICIOUS    TRUE
#define MUX_MUS_VICTORY_AQUA_MAGMA      TRUE
#define MUX_MUS_CABLE_CAR               TRUE
#define MUX_MUS_GAME_CORNER             TRUE
#define MUX_MUS_DEWFORD                 TRUE
#define MUX_MUS_SAFARI_ZONE             TRUE
#define MUX_MUS_VICTORY_ROAD            TRUE
#define MUX_MUS_AQUA_MAGMA_HIDEOUT      TRUE
#define MUX_MUS_SAILING                 TRUE
#define MUX_MUS_MT_PYRE                 TRUE
#define MUX_MUS_SLATEPORT               TRUE
#define MUX_MUS_MT_PYRE_EXTERIOR        TRUE
#define MUX_MUS_SCHOOL                  TRUE
#define MUX_MUS_HALL_OF_FAME            TRUE
#define MUX_MUS_FALLARBOR               TRUE
#define MUX_MUS_SEALED_CHAMBER          TRUE
#define MUX_MUS_CONTEST_WINNER          TRUE
#define MUX_MUS_CONTEST                 TRUE
#define MUX_MUS_ENCOUNTER_MAGMA         TRUE
#define MUX_MUS_INTRO_BATTLE            TRUE
#define MUX_MUS_ABNORMAL_WEATHER        TRUE
#define MUX_MUS_WEATHER_GROUDON         FALSE
#define MUX_MUS_SOOTOPOLIS              TRUE
#define MUX_MUS_CONTEST_RESULTS         TRUE
#define MUX_MUS_HALL_OF_FAME_ROOM       TRUE
#define MUX_MUS_TRICK_HOUSE             TRUE
#define MUX_MUS_ENCOUNTER_TWINS         TRUE
#define MUX_MUS_ENCOUNTER_ELITE_FOUR    TRUE
#define MUX_MUS_ENCOUNTER_HIKER         TRUE
#define MUX_MUS_CONTEST_LOBBY           TRUE
#define MUX_MUS_ENCOUNTER_INTERVIEWER   TRUE
#define MUX_MUS_ENCOUNTER_CHAMPION      TRUE
#define MUX_MUS_CREDITS                 TRUE
#define MUX_MUS_END                     TRUE
#define MUX_MUS_B_FRONTIER              TRUE
#define MUX_MUS_B_ARENA                 TRUE
#define MUX_MUS_OBTAIN_B_POINTS         TRUE
#define MUX_MUS_REGISTER_MATCH_CALL     TRUE
#define MUX_MUS_B_PYRAMID               TRUE
#define MUX_MUS_B_PYRAMID_TOP           TRUE
#define MUX_MUS_B_PALACE                TRUE
#define MUX_MUS_RAYQUAZA_APPEARS        TRUE
#define MUX_MUS_B_TOWER                 TRUE
#define MUX_MUS_OBTAIN_SYMBOL           TRUE
#define MUX_MUS_B_DOME                  TRUE
#define MUX_MUS_B_PIKE                  TRUE
#define MUX_MUS_B_FACTORY               TRUE
#define MUX_MUS_VS_RAYQUAZA             TRUE
#define MUX_MUS_VS_FRONTIER_BRAIN       TRUE
#define MUX_MUS_VS_MEW                  TRUE
#define MUX_MUS_B_DOME_LOBBY            TRUE
#define MUX_MUS_VS_WILD                 TRUE
#define MUX_MUS_VS_AQUA_MAGMA           TRUE
#define MUX_MUS_VS_TRAINER              TRUE
#define MUX_MUS_VS_GYM_LEADER           TRUE
#define MUX_MUS_VS_CHAMPION             TRUE
#define MUX_MUS_VS_REGI                 TRUE
#define MUX_MUS_VS_KYOGRE_GROUDON       TRUE
#define MUX_MUS_VS_RIVAL                TRUE
#define MUX_MUS_VS_ELITE_FOUR           TRUE
#define MUX_MUS_VS_AQUA_MAGMA_LEADER    TRUE

// FireRed / LeafGreen music
#define MUX_MUS_RG_FOLLOW_ME            FALSE
#define MUX_MUS_RG_GAME_CORNER          TRUE
#define MUX_MUS_RG_ROCKET_HIDEOUT       FALSE
#define MUX_MUS_RG_GYM                  FALSE
#define MUX_MUS_RG_JIGGLYPUFF           FALSE
#define MUX_MUS_RG_INTRO_FIGHT          FALSE
#define MUX_MUS_RG_TITLE                FALSE
#define MUX_MUS_RG_CINNABAR             FALSE
#define MUX_MUS_RG_LAVENDER             FALSE
#define MUX_MUS_RG_HEAL                 FALSE
#define MUX_MUS_RG_CYCLING              FALSE
#define MUX_MUS_RG_ENCOUNTER_ROCKET     FALSE
#define MUX_MUS_RG_ENCOUNTER_GIRL       FALSE
#define MUX_MUS_RG_ENCOUNTER_BOY        FALSE
#define MUX_MUS_RG_HALL_OF_FAME         FALSE
#define MUX_MUS_RG_VIRIDIAN_FOREST      FALSE
#define MUX_MUS_RG_MT_MOON              FALSE
#define MUX_MUS_RG_POKE_MANSION         FALSE
#define MUX_MUS_RG_CREDITS              FALSE
#define MUX_MUS_RG_ROUTE1               FALSE
#define MUX_MUS_RG_ROUTE24              FALSE
#define MUX_MUS_RG_ROUTE3               FALSE
#define MUX_MUS_RG_ROUTE11              FALSE
#define MUX_MUS_RG_VICTORY_ROAD         FALSE
#define MUX_MUS_RG_VS_GYM_LEADER        FALSE
#define MUX_MUS_RG_VS_TRAINER           FALSE
#define MUX_MUS_RG_VS_WILD              FALSE
#define MUX_MUS_RG_VS_CHAMPION          FALSE
#define MUX_MUS_RG_PALLET               FALSE
#define MUX_MUS_RG_OAK_LAB              FALSE
#define MUX_MUS_RG_OAK                  FALSE
#define MUX_MUS_RG_POKE_CENTER          FALSE
#define MUX_MUS_RG_SS_ANNE              FALSE
#define MUX_MUS_RG_SURF                 FALSE
#define MUX_MUS_RG_POKE_TOWER           FALSE
#define MUX_MUS_RG_SILPH                FALSE
#define MUX_MUS_RG_FUCHSIA              FALSE
#define MUX_MUS_RG_CELADON              FALSE
#define MUX_MUS_RG_VICTORY_TRAINER      FALSE
#define MUX_MUS_RG_VICTORY_WILD         TRUE
#define MUX_MUS_RG_VICTORY_GYM_LEADER   FALSE
#define MUX_MUS_RG_VERMILLION           FALSE
#define MUX_MUS_RG_PEWTER               FALSE
#define MUX_MUS_RG_ENCOUNTER_RIVAL      FALSE
#define MUX_MUS_RG_RIVAL_EXIT           FALSE
#define MUX_MUS_RG_DEX_RATING           TRUE
#define MUX_MUS_RG_OBTAIN_KEY_ITEM      TRUE
#define MUX_MUS_RG_CAUGHT_INTRO         TRUE
#define MUX_MUS_RG_PHOTO                FALSE
#define MUX_MUS_RG_GAME_FREAK           FALSE
#define MUX_MUS_RG_CAUGHT               FALSE
#define MUX_MUS_RG_NEW_GAME_INSTRUCT    FALSE
#define MUX_MUS_RG_NEW_GAME_INTRO       FALSE
#define MUX_MUS_RG_NEW_GAME_EXIT        FALSE
#define MUX_MUS_RG_POKE_JUMP            TRUE
#define MUX_MUS_RG_UNION_ROOM           FALSE
#define MUX_MUS_RG_NET_CENTER           FALSE
#define MUX_MUS_RG_MYSTERY_GIFT         TRUE
#define MUX_MUS_RG_BERRY_PICK           TRUE
#define MUX_MUS_RG_SEVII_CAVE           TRUE
#define MUX_MUS_RG_TEACHY_TV_SHOW       FALSE
#define MUX_MUS_RG_SEVII_ROUTE          TRUE
#define MUX_MUS_RG_SEVII_DUNGEON        FALSE
#define MUX_MUS_RG_SEVII_123            FALSE
#define MUX_MUS_RG_SEVII_45             FALSE
#define MUX_MUS_RG_SEVII_67             FALSE
#define MUX_MUS_RG_POKE_FLUTE           TRUE
#define MUX_MUS_RG_VS_DEOXYS            TRUE
#define MUX_MUS_RG_VS_MEWTWO            FALSE
#define MUX_MUS_RG_VS_LEGEND            TRUE
#define MUX_MUS_RG_ENCOUNTER_GYM_LEADER FALSE
#define MUX_MUS_RG_ENCOUNTER_DEOXYS     TRUE
#define MUX_MUS_RG_TRAINER_TOWER        FALSE
#define MUX_MUS_RG_SLOW_PALLET          FALSE
#define MUX_MUS_RG_TEACHY_TV_MENU       FALSE

#endif // GUARD_CONFIG_MUSIC_EXPANSION_V3_H
