LavaridgeTown_EventScript_Sparkle_IceHeal::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_LAVARIDGE_TOWN_ICE_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 4, 5, 0
	setvar VAR_TEMP_00, 1
	end

TrickHouseEnd_EventScript_Sparkle_Nugget::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_TRICK_HOUSE_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 4, 5, 0
	setvar VAR_TEMP_00, 1
	end

Route111_EventScript_Sparkle_Stardust::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_111_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 26, 70, 0
	setvar VAR_TEMP_00, 1
	end

Route111_EventScript_Sparkle_Protein::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_111_PROTEIN, EventScript_ReleaseEnd
	dofieldeffectsparkle 19, 55, 0
	setvar VAR_TEMP_01, 1
	end

Route111_EventScript_Sparkle_RareCandy::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_111_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 35, 66, 0
	setvar VAR_TEMP_02, 1
	end

Route113_EventScript_Sparkle_Ether::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_113_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 66, 3, 0
	setvar VAR_TEMP_00, 1
	end

Route113_EventScript_Sparkle_Nugget::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_113_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 73, 3, 0
	setvar VAR_TEMP_01, 1
	end

Route114_EventScript_Sparkle_Carbos::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_114_CARBOS, EventScript_ReleaseEnd
	dofieldeffectsparkle 20, 57, 0
	setvar VAR_TEMP_00, 1
	end

Route114_EventScript_Sparkle_Revive::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_114_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 30, 0
	setvar VAR_TEMP_01, 1
	end

Route119_EventScript_Sparkle_Calcium::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_119_CALCIUM, EventScript_ReleaseEnd
	dofieldeffectsparkle 17, 82, 0
	setvar VAR_TEMP_00, 1
	end

Route119_EventScript_Sparkle_UltraBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_119_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 38, 63, 0
	setvar VAR_TEMP_01, 1
	end

Route119_EventScript_Sparkle_FullHeal::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_119_FULL_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 26, 120, 0
	setvar VAR_TEMP_02, 1
	end

Route119_EventScript_Sparkle_MaxEther::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_119_MAX_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 20, 29, 0
	setvar VAR_TEMP_03, 1
	end

Route123_EventScript_Sparkle_SuperRepel::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_123_SUPER_REPEL, EventScript_ReleaseEnd
	dofieldeffectsparkle 75, 1, 0
	setvar VAR_TEMP_00, 1
	end

Route123_EventScript_Sparkle_Revive::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_123_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 1, 0
	setvar VAR_TEMP_01, 1
	end

Route123_EventScript_Sparkle_HyperPotion::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_123_HYPER_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 91, 15, 0
	setvar VAR_TEMP_02, 1
	end

Route123_EventScript_Sparkle_PPUp::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_123_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 139, 15, 0
	setvar VAR_TEMP_03, 1
	end

Route123_EventScript_Sparkle_RareCandy::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_123_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 138, 18, 0
	setvar VAR_TEMP_04, 1
	end

Underwater_Route124_EventScript_Sparkle_Carbos::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_CARBOS, EventScript_ReleaseEnd
	dofieldeffectsparkle 42, 51, 0
	setvar VAR_TEMP_00, 1
	end

Underwater_Route124_EventScript_Sparkle_GreenShard::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_GREEN_SHARD, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 40, 0
	setvar VAR_TEMP_01, 1
	end

Underwater_Route124_EventScript_Sparkle_Pearl::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 66, 34, 0
	setvar VAR_TEMP_02, 1
	end

Underwater_Route124_EventScript_Sparkle_BigPearl::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_BIG_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 64, 54, 0
	setvar VAR_TEMP_03, 1
	end

Underwater_Route124_EventScript_Sparkle_HeartScale1::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_1, EventScript_ReleaseEnd
	dofieldeffectsparkle 70, 64, 0
	setvar VAR_TEMP_04, 1
	end

Underwater_Route124_EventScript_Sparkle_Calcium::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_CALCIUM, EventScript_ReleaseEnd
	dofieldeffectsparkle 42, 5, 0
	setvar VAR_TEMP_05, 1
	end

Underwater_Route124_EventScript_Sparkle_HeartScale2::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 45, 36, 0
	setvar VAR_TEMP_06, 1
	end

Underwater_Route126_EventScript_Sparkle_BlueShard::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_BLUE_SHARD, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 77, 0
	setvar VAR_TEMP_00, 1
	end

Underwater_Route126_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 30, 17, 0
	setvar VAR_TEMP_01, 1
	end

Underwater_Route126_EventScript_Sparkle_UltraBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 41, 19, 0
	setvar VAR_TEMP_02, 1
	end

Underwater_Route126_EventScript_Sparkle_Stardust::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 63, 19, 0
	setvar VAR_TEMP_03, 1
	end

Underwater_Route126_EventScript_Sparkle_Pearl::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 10, 36, 0
	setvar VAR_TEMP_04, 1
	end

Underwater_Route126_EventScript_Sparkle_YellowShard::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_YELLOW_SHARD, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 35, 0
	setvar VAR_TEMP_05, 1
	end

Underwater_Route126_EventScript_Sparkle_Iron::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_IRON, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 39, 0
	setvar VAR_TEMP_06, 1
	end

Underwater_Route126_EventScript_Sparkle_BigPearl::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_126_BIG_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 65, 60, 0
	setvar VAR_TEMP_07, 1
	end

Underwater_Route127_EventScript_Sparkle_StarPiece::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_127_STAR_PIECE, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 42, 0
	setvar VAR_TEMP_00, 1
	end

Underwater_Route127_EventScript_Sparkle_HPUp::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_127_HP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 50, 36, 0
	setvar VAR_TEMP_01, 1
	end

Underwater_Route127_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_127_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 34, 72, 0
	setvar VAR_TEMP_02, 1
	end

Underwater_Route127_EventScript_Sparkle_RedShard::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_127_RED_SHARD, EventScript_ReleaseEnd
	dofieldeffectsparkle 72, 20, 0
	setvar VAR_TEMP_03, 1
	end

Underwater_Route128_EventScript_Sparkle_Protein::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_128_PROTEIN, EventScript_ReleaseEnd
	dofieldeffectsparkle 38, 19, 0
	setvar VAR_TEMP_00, 1
	end

Underwater_Route128_EventScript_Sparkle_Pearl::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_UNDERWATER_128_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 69, 18, 0
	setvar VAR_TEMP_01, 1
	end

LilycoveCity_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_LILYCOVE_CITY_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 36, 31, 0
	setvar VAR_TEMP_00, 1
	end

LilycoveCity_EventScript_Sparkle_PPUp::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_LILYCOVE_CITY_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 61, 7, 0
	setvar VAR_TEMP_01, 1
	end

LilycoveCity_EventScript_Sparkle_PokeBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_LILYCOVE_CITY_POKE_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 64, 31, 0
	setvar VAR_TEMP_02, 1
	end

FallarborTown_EventScript_Sparkle_Nugget::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_FALLARBOR_TOWN_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 2, 15, 0
	setvar VAR_TEMP_00, 1
	end

MtPyre_Exterior_EventScript_Sparkle_UltraBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 8, 0
	setvar VAR_TEMP_00, 1
	end

MtPyre_Exterior_EventScript_Sparkle_MaxEther::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_MAX_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 22, 0
	setvar VAR_TEMP_01, 1
	end

MtPyre_Summit_EventScript_Sparkle_Zinc::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_ZINC, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 25, 0
	setvar VAR_TEMP_00, 1
	end

MtPyre_Summit_EventScript_Sparkle_RareCandy::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 37, 7, 0
	setvar VAR_TEMP_01, 1
	end

SSTidalLowerDeck_EventScript_Sparkle_Leftovers::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_SS_TIDAL_LOWER_DECK_LEFTOVERS, EventScript_ReleaseEnd
	dofieldeffectsparkle 0, 2, 0
	setvar VAR_TEMP_00, 1
	end

Route104_EventScript_Sparkle_Potion::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_104_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 55, 0
	setvar VAR_TEMP_00, 1
	end

Route104_EventScript_Sparkle_SuperPotion::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_104_SUPER_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 6, 0
	setvar VAR_TEMP_01, 1
	end

Route104_EventScript_Sparkle_PokeBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_104_POKE_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 9, 0
	setvar VAR_TEMP_02, 1
	end

Route104_EventScript_Sparkle_Antidote::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_104_ANTIDOTE, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 72, 0
	setvar VAR_TEMP_03, 1
	end

Route104_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_104_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 64, 0
	setvar VAR_TEMP_04, 1
	end

Route121_EventScript_Sparkle_HPUp::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_121_HP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 23, 10, 0
	setvar VAR_TEMP_00, 1
	end

Route121_EventScript_Sparkle_Nugget::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_121_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 58, 3, 0
	setvar VAR_TEMP_01, 1
	end

Route121_EventScript_Sparkle_FullHeal::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_121_FULL_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 72, 5, 0
	setvar VAR_TEMP_02, 1
	end

Route121_EventScript_Sparkle_MaxRevive::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_121_MAX_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 68, 8, 0
	setvar VAR_TEMP_03, 1
	end

Route116_EventScript_Sparkle_SuperPotion::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_116_SUPER_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 22, 9, 0
	setvar VAR_TEMP_00, 1
	end

Route116_EventScript_SetVarTempItem0To0::
	setvar VAR_TEMP_00, 0
	end

Route116_EventScript_Sparkle_BlackGlasses::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_116_BLACK_GLASSES, EventScript_ReleaseEnd
	dofieldeffectsparkle 70, 13, 0
	setvar VAR_TEMP_01, 1
	end

Route106_EventScript_Sparkle_Stardust::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_106_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 53, 12, 0
	setvar VAR_TEMP_00, 1
	end

Route106_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_106_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 68, 15, 0
	setvar VAR_TEMP_01, 1
	end

Route106_EventScript_Sparkle_PokeBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_106_POKE_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 41, 11, 0
	setvar VAR_TEMP_02, 1
	end

GraniteCave_B2F_EventScript_Sparkle_Everstone1::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_1, EventScript_ReleaseEnd
	dofieldeffectsparkle 28, 6, 0
	setvar VAR_TEMP_00, 1
	end

GraniteCave_B2F_EventScript_Sparkle_Everstone2::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 11, 0
	setvar VAR_TEMP_01, 1
	end

Route109_EventScript_Sparkle_Revive::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_109_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 23, 0
	setvar VAR_TEMP_00, 1
	end

Route109_EventScript_Sparkle_GreatBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_109_GREAT_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 10, 0
	setvar VAR_TEMP_01, 1
	end

Route109_EventScript_Sparkle_HeartScale1::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_1, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 5, 0
	setvar VAR_TEMP_02, 1
	end

Route109_EventScript_Sparkle_Ether::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_109_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 28, 20, 0
	setvar VAR_TEMP_03, 1
	end

Route109_EventScript_Sparkle_HeartScale2::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 16, 0
	setvar VAR_TEMP_04, 1
	end

Route109_EventScript_Sparkle_HeartScale3::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_3, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 42, 0
	setvar VAR_TEMP_05, 1
	end

Route110_EventScript_Sparkle_GreatBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_110_GREAT_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 45, 0
	setvar VAR_TEMP_00, 1
	end

Route110_EventScript_Sparkle_Revive::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_110_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 35, 39, 0
	setvar VAR_TEMP_01, 1
	end

Route110_EventScript_Sparkle_FullHeal::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_110_FULL_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 37, 67, 0
	setvar VAR_TEMP_02, 1
	end

Route110_EventScript_Sparkle_PokeBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_110_POKE_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 4, 35, 0
	setvar VAR_TEMP_03, 1
	end

PetalburgWoods_EventScript_Sparkle_Potion::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 39, 35, 0
	setvar VAR_TEMP_00, 1
	end

PetalburgWoods_EventScript_Sparkle_TinyMushroom1::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_1, EventScript_ReleaseEnd
	dofieldeffectsparkle 26, 6, 0
	setvar VAR_TEMP_01, 1
	end

PetalburgWoods_EventScript_Sparkle_TinyMushroom2::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 40, 29, 0
	setvar VAR_TEMP_02, 1
	end

PetalburgWoods_EventScript_Sparkle_PokeBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POKE_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 4, 19, 0
	setvar VAR_TEMP_03, 1
	end

Route118_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_118_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 14, 0
	setvar VAR_TEMP_00, 1
	end

Route118_EventScript_Sparkle_Iron::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_118_IRON, EventScript_ReleaseEnd
	dofieldeffectsparkle 31, 13, 0
	setvar VAR_TEMP_01, 1
	end

Route120_EventScript_Sparkle_RareCandy2::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 0, 86, 0
	setvar VAR_TEMP_00, 1
	end

Route120_EventScript_Sparkle_Zinc::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_120_ZINC, EventScript_ReleaseEnd
	dofieldeffectsparkle 24, 42, 0
	setvar VAR_TEMP_01, 1
	end

Route120_EventScript_Sparkle_RareCandy1::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_1, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 1, 0
	setvar VAR_TEMP_02, 1
	end

Route120_EventScript_Sparkle_Revive::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_120_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 31, 11, 0
	setvar VAR_TEMP_03, 1
	end

Route117_EventScript_Sparkle_Repel::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_117_REPEL, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 18, 0
	setvar VAR_TEMP_00, 1
	end

JaggedPass_EventScript_Sparkle_GreatBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_JAGGED_PASS_GREAT_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 29, 0
	setvar VAR_TEMP_00, 1
	end

JaggedPass_EventScript_Sparkle_FullHeal::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_JAGGED_PASS_FULL_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 10, 0
	setvar VAR_TEMP_01, 1
	end

VictoryRoad_1F_EventScript_Sparkle_UltraBall::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 30, 39, 0
	setvar VAR_TEMP_00, 1
	end

VictoryRoad_B2F_EventScript_Sparkle_Elixir::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 28, 5, 0
	setvar VAR_TEMP_00, 1
	end

VictoryRoad_B2F_EventScript_Sparkle_MaxRepel::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_MAX_REPEL, EventScript_ReleaseEnd
	dofieldeffectsparkle 37, 1, 0
	setvar VAR_TEMP_01, 1
	end

Route108_EventScript_Sparkle_RareCandy::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_108_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 38, 14, 0
	setvar VAR_TEMP_00, 1
	end

Route105_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_105_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 68, 0
	setvar VAR_TEMP_00, 1
	end

Route105_EventScript_Sparkle_BigPearl::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_105_BIG_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 56, 0
	setvar VAR_TEMP_01, 1
	end

Route128_EventScript_Sparkle_HeartScale1::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_1, EventScript_ReleaseEnd
	dofieldeffectsparkle 49, 9, 0
	setvar VAR_TEMP_00, 1
	end

Route128_EventScript_Sparkle_HeartScale2::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 57, 21, 0
	setvar VAR_TEMP_01, 1
	end

Route128_EventScript_Sparkle_HeartScale3::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_3, EventScript_ReleaseEnd
	dofieldeffectsparkle 31, 33, 0
	setvar VAR_TEMP_02, 1
	end

PetalburgCity_EventScript_Sparkle_RareCandy::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_PETALBURG_CITY_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 29, 0
	setvar VAR_TEMP_00, 1
	end

Route115_EventScript_Sparkle_HeartScale::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_115_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 49, 0
	setvar VAR_TEMP_00, 1
	end

SafariZone_Southeast_EventScript_Sparkle_FullRestore::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_FULL_RESTORE, EventScript_ReleaseEnd
	dofieldeffectsparkle 32, 33, 0
	setvar VAR_TEMP_00, 1
	end

SafariZone_Southeast_EventScript_Sparkle_PPUp::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 19, 36, 0
	setvar VAR_TEMP_01, 1
	end

SafariZone_Northeast_EventScript_Sparkle_RareCandy::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 31, 35, 0
	setvar VAR_TEMP_00, 1
	end

SafariZone_Northeast_EventScript_Sparkle_Zinc::
	goto_if_unset FLAG_HIDDEN_ITEM_SPARKLES, EventScript_ReleaseEnd
	goto_if_set FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_ZINC, EventScript_ReleaseEnd
	dofieldeffectsparkle 21, 5, 0
	setvar VAR_TEMP_01, 1
	end

SafariZone_Northeast_EventScript_SetVarTempItem1To0::
	setvar VAR_TEMP_01, 0
	end
