voice_group ut_001
	voice_directsound 60, 0, DirectSoundSynthData_squ25, 255, 235, 60, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ25, 255, 235, 80, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ25, 35, 0, 255, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ12, 255, 235, 60, 0
	voice_square_2 60, 0, 2, 0, 3, 4, 0
	voice_noise 60, 0, 0, 0, 2, 0, 0
    voice_programmable_wave 60, 0, ProgrammableWaveData_nesTri, 0, 7, 15, 0
