voice_group ut_004
	voice_directsound 60, 0, DirectSoundWaveData_eb_mellowpiano, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_onettbass, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_savetheminerspad, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_mellowpiano, 255, 254, 25, 192
	voice_directsound 60, 0, DirectSoundWaveData_ct_panflute, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_ct_strings, 60, 0, 255, 0
