voice_group ut_006
	voice_directsound 72, 0, DirectSoundWaveData_sinewave_c5, 255, 247, 64, 100
	voice_directsound 60, 0, DirectSoundWaveData_ct_piano, 255, 251, 0, 100
	voice_directsound 60, 0, DirectSoundWaveData_eb_pokeybass, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_eb_subsine, 255, 0, 255, 0
	voice_keysplit_all voicegroup_perc_006 - 0xc * 36

voice_group perc_006
	voice_directsound 62, 64, DirectSoundWaveData_roomkick, 255, 234, 64, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 62, 64, DirectSoundWaveData_roomsnare, 255, 244, 100, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 57, 64, DirectSoundWaveData_fingersnap, 255, 0, 255, 127
