voice_group ut_018
	voice_directsound 72, 0, DirectSoundWaveData_celesta_c5, 255, 248, 0, 230
	voice_keysplit voicegroup_tubularbell, keysplit_2oct - 13 - 3
	voice_directsound 72, 0, DirectSoundWaveData_sinewave_c5, 255, 0, 255, 100
	voice_directsound 60, 0, DirectSoundWaveData_windchime_c4, 255, 0, 255, 240
	voice_directsound 60, 0, DirectSoundWaveData_ct_rhodes, 255, 0, 255, 127
	voice_square_2 60, 0, 1, 2, 0, 15, 0
	voice_square_1 60, 0, 0, 0, 2, 0, 15, 0
	voice_square_1 60, 0, 0, 0, 0, 0, 15, 0
    voice_programmable_wave 60, 0, ProgrammableWaveData_SynString, 0, 0, 15, 0
