voice_group ut_018
	voice_directsound 72, 0, DirectSoundWaveData_celesta_c5, 255, 245, 0, 230
	voice_keysplit voicegroup_tubularbell, keysplit_2oct - 13 - 3
	voice_directsound 72, 0, DirectSoundWaveData_sinewave_c5, 255, 0, 255, 100
	voice_directsound 60, 0, DirectSoundWaveData_windchime_c4, 255, 0, 255, 240
	voice_directsound 60, 0, DirectSoundWaveData_ct_rhodes, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_synstr1_ch_maj7, 30, 0, 255, 240
	voice_directsound 60, 0, DirectSoundWaveData_synstr1_ch_min7, 30, 0, 255, 240
